import { Id } from './id';
import { Name } from './name';
import { Skill, SkillEnum } from '../skills/skill';
import quest from './quest';

const all_quests: quest[] = [
  {
    id: Id('A-Souls-Bane'),
    name: Name("A Soul's Bane"),
    wiki_url: 'https://oldschool.runescape.wiki/w/A_Soul%27s_Bane',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Defence), amount: 500 },
        { skill: Skill(SkillEnum.Hitpoints), amount: 500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('A-Tail-of-Two-Cats'),
    name: Name('A Tail of Two Cats'),
    wiki_url: 'https://oldschool.runescape.wiki/w/A_Tail_of_Two_Cats',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Dragonkin',
    requirements: { quests: ["Icthlarin's Little Helper"], levels: [] },
    rewards: { experience: [], quest_points: 2 },
  },
  {
    id: Id('A-Taste-of-Hope'),
    name: Name('A Taste of Hope'),
    wiki_url: 'https://oldschool.runescape.wiki/w/A_Taste_of_Hope',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Myreque',
    requirements: {
      quests: ['Darkness of Hallowvale'],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 48, boostable: false },
        { skill: Skill(SkillEnum.Agility), level: 45, boostable: false },
        { skill: Skill(SkillEnum.Attack), level: 40, boostable: false },
        { skill: Skill(SkillEnum.Herblore), level: 40, boostable: false },
        { skill: Skill(SkillEnum.Slayer), level: 38, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: Id('Animal-Magnetism'),
    name: Name('Animal Magnetism'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Animal_Magnetism',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: null,
    requirements: {
      quests: ['The Restless Ghost', 'Ernest the Chicken', 'Priest in Peril'],
      levels: [
        { skill: Skill(SkillEnum.Slayer), level: 18, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 19, boostable: false },
        { skill: Skill(SkillEnum.Ranged), level: 30, boostable: false },
        { skill: Skill(SkillEnum.Woodcutting), level: 35, boostable: false },
        { skill: Skill(SkillEnum.Prayer), level: 31, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 1000 },
        { skill: Skill(SkillEnum.Fletching), amount: 1000 },
        { skill: Skill(SkillEnum.Slayer), amount: 1000 },
        { skill: Skill(SkillEnum.Woodcutting), amount: 2500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Another-Slice-of-HAM'),
    name: Name('Another Slice of H.A.M.'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Another_Slice_of_H.A.M.',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Dorgeshuun (#4)',
    requirements: {
      quests: [
        'Death to the Dorgeshuun',
        'The Giant Dwarf',
        'The Dig Site',
        'Druidic Ritual',
      ],
      levels: [
        { skill: Skill(SkillEnum.Attack), level: 15, boostable: false },
        { skill: Skill(SkillEnum.Prayer), level: 25, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Mining), amount: 3000 },
        { skill: Skill(SkillEnum.Prayer), amount: 3000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Between-a-Rock'),
    name: Name('Between a Rock...'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Between_a_Rock...',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium - Long',
    series: 'Rise of the Red Axe',
    requirements: {
      quests: ['Dwarf Cannon', 'Fishing Contest'],
      levels: [
        { skill: Skill(SkillEnum.Defence), level: 30, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 40, boostable: true },
        { skill: Skill(SkillEnum.Smithing), level: 50, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Defence), amount: 5000 },
        { skill: Skill(SkillEnum.Mining), amount: 5000 },
        { skill: Skill(SkillEnum.Smithing), amount: 5000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Big-Chompy-Bird-Hunting'),
    name: Name('Big Chompy Bird Hunting'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Big_Chompy_Bird_Hunting',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: 'Ogre',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Fletching), level: 5, boostable: false },
        { skill: Skill(SkillEnum.Cooking), level: 30, boostable: false },
        { skill: Skill(SkillEnum.Ranged), level: 30, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Cooking), amount: 1470 },
        { skill: Skill(SkillEnum.Fletching), amount: 262 },
        { skill: Skill(SkillEnum.Ranged), amount: 735 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Biohazard'),
    name: Name('Biohazard'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Biohazard',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Elf',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Thieving), amount: 1250 }],
      quest_points: 3,
    },
  },
  {
    id: Id('Black-Knights-Fortress'),
    name: Name("Black Knights' Fortress"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Black_Knights%27_Fortress',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Quest_points), level: 12, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 3 },
  },
  {
    id: Id('Bone-Voyage'),
    name: Name('Bone Voyage'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Bone_Voyage',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Medium',
    series: null,
    requirements: { quests: ['The Dig Site'], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: Id('Cabin-Fever'),
    name: Name('Cabin Fever'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Cabin_Fever',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Pirate',
    requirements: {
      quests: ["Pirate's Treasure", 'Rum Deal', 'Priest in Peril'],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 42, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 45, boostable: false },
        { skill: Skill(SkillEnum.Smithing), level: 50, boostable: false },
        { skill: Skill(SkillEnum.Ranged), level: 40, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 7000 },
        { skill: Skill(SkillEnum.Crafting), amount: 7000 },
        { skill: Skill(SkillEnum.Smithing), amount: 7000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Client-of-Kourend'),
    name: Name('Client of Kourend'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Client_of_Kourend',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium (15-20 minutes)',
    series: 'Great Kourend',
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: Id('Clock-Tower'),
    name: Name('Clock Tower'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Clock_Tower',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: Id('Cold-War'),
    name: Name('Cold War'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Cold_War',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: 'Penguin',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Hunter), level: 10, boostable: false },
        { skill: Skill(SkillEnum.Agility), level: 30, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 30, boostable: false },
        { skill: Skill(SkillEnum.Construction), level: 34, boostable: false },
        { skill: Skill(SkillEnum.Thieving), level: 15, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 5000 },
        { skill: Skill(SkillEnum.Construction), amount: 1500 },
        { skill: Skill(SkillEnum.Crafting), amount: 2000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Contact'),
    name: Name('Contact!'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Contact!',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Medium',
    series: 'Desert',
    requirements: {
      quests: ['Prince Ali Rescue', "Icthlarin's Little Helper"],
      levels: [],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Thieving), amount: 7000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Cooks-Assistant'),
    name: Name("Cook's Assistant"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Cook%27s_Assistant',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short (<5 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Cooking), amount: 300 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Creature-of-Fenkenstrain'),
    name: Name('Creature of Fenkenstrain'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Creature_of_Fenkenstrain',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: null,
    requirements: {
      quests: ['Priest in Peril', 'The Restless Ghost'],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Thieving), level: 25, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Thieving), amount: 1000 }],
      quest_points: 2,
    },
  },
  {
    id: Id('Darkness-of-Hallowvale'),
    name: Name('Darkness of Hallowvale'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Darkness_of_Hallowvale',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Very long',
    series: 'Myreque',
    requirements: {
      quests: ['In Aid of the Myreque'],
      levels: [
        { skill: Skill(SkillEnum.Construction), level: 5, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 20, boostable: true },
        { skill: Skill(SkillEnum.Thieving), level: 22, boostable: false },
        { skill: Skill(SkillEnum.Agility), level: 26, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 32, boostable: false },
        { skill: Skill(SkillEnum.Magic), level: 33, boostable: false },
        { skill: Skill(SkillEnum.Strength), level: 40, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 7000 },
        { skill: Skill(SkillEnum.Construction), amount: 2000 },
        { skill: Skill(SkillEnum.Thieving), amount: 6000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Death-Plateau'),
    name: Name('Death Plateau'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Death_Plateau',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Troll',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Attack), amount: 3000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Death-to-the-Dorgeshuun'),
    name: Name('Death to the Dorgeshuun'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Death_to_the_Dorgeshuun',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Dorgeshuun',
    requirements: {
      quests: ['The Lost Tribe'],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 23, boostable: false },
        { skill: Skill(SkillEnum.Thieving), level: 23, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Ranged), amount: 2000 },
        { skill: Skill(SkillEnum.Thieving), amount: 2000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Demon-Slayer'),
    name: Name('Demon Slayer'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Demon_Slayer',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 3 },
  },
  {
    id: Id('Desert-Treasure'),
    name: Name('Desert Treasure'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Desert_Treasure',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Very long',
    series: 'The Return of Zaros and Mahjarrat',
    requirements: {
      quests: [
        'The Dig Site',
        'Temple of Ikov',
        'The Tourist Trap',
        'Troll Stronghold',
        'Priest in Peril',
        'Waterfall Quest',
      ],
      levels: [
        { skill: Skill(SkillEnum.Thieving), level: 53, boostable: true },
        { skill: Skill(SkillEnum.Firemaking), level: 50, boostable: false },
        { skill: Skill(SkillEnum.Slayer), level: 10, boostable: false },
        { skill: Skill(SkillEnum.Magic), level: 50, boostable: true },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Magic), amount: 20000 }],
      quest_points: 3,
    },
  },
  {
    id: Id('Devious-Minds'),
    name: Name('Devious Minds'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Devious_Minds',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short',
    series: 'The Return of Zaros',
    requirements: {
      quests: [
        'Wanted!',
        'Troll Stronghold',
        "Doric's Quest",
        'Enter the Abyss',
      ],
      levels: [
        { skill: Skill(SkillEnum.Smithing), level: 65, boostable: true },
        { skill: Skill(SkillEnum.Runecraft), level: 50, boostable: false },
        { skill: Skill(SkillEnum.Fletching), level: 50, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Fletching), amount: 5000 },
        { skill: Skill(SkillEnum.Runecraft), amount: 5000 },
        { skill: Skill(SkillEnum.Smithing), amount: 6500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Dorics-Quest'),
    name: Name("Doric's Quest"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Doric%27s_Quest',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: Skill(SkillEnum.Mining), level: 15, boostable: false }],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Mining), amount: 1300 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Dragon-Slayer'),
    name: Name('Dragon Slayer'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Dragon_Slayer',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Guild',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Quest_points), level: 32, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 8, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Defence), amount: 18650 },
        { skill: Skill(SkillEnum.Strength), amount: 18650 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Dragon-Slayer-II'),
    name: Name('Dragon Slayer II'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Dragon_Slayer_II',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Grandmaster',
    length: 'Very long',
    series: 'Dragonkin',
    requirements: {
      quests: [
        "Legends' Quest",
        'Dream Mentor',
        'A Tail of Two Cats',
        'Animal Magnetism',
        'Ghosts Ahoy',
        'Bone Voyage',
        'Client of Kourend',
      ],
      levels: [
        { skill: Skill(SkillEnum.Quest_points), level: 200, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 15000 },
        { skill: Skill(SkillEnum.Mining), amount: 18000 },
        { skill: Skill(SkillEnum.Smithing), amount: 25000 },
        { skill: Skill(SkillEnum.Thieving), amount: 15000 },
      ],
      quest_points: 5,
    },
  },
  {
    id: Id('Dream-Mentor'),
    name: Name('Dream Mentor'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Dream_Mentor',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Short - Medium',
    series: 'Fremennik',
    requirements: {
      quests: ['Lunar Diplomacy', "Eadgar's Ruse"],
      levels: [{ skill: Skill(SkillEnum.Combat), level: 85, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Hitpoints), amount: 15000 },
        { skill: Skill(SkillEnum.Magic), amount: 10000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Druidic-Ritual'),
    name: Name('Druidic Ritual'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Druidic_Ritual',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Herblore), amount: 250 }],
      quest_points: 4,
    },
  },
  {
    id: Id('Dwarf-Cannon'),
    name: Name('Dwarf Cannon'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Dwarf_Cannon',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Crafting), amount: 750 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Eadgars-Ruse'),
    name: Name("Eadgar's Ruse"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Eadgar%27s_Ruse',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium - Long',
    series: 'Troll',
    requirements: {
      quests: ['Druidic Ritual', 'Troll Stronghold'],
      levels: [
        { skill: Skill(SkillEnum.Herblore), level: 31, boostable: true },
        { skill: Skill(SkillEnum.Agility), level: 44, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Herblore), amount: 11000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Eagles-Peak'),
    name: Name("Eagles' Peak"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Eagles%27_Peak',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: Skill(SkillEnum.Hunter), level: 27, boostable: true }],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Hunter), amount: 2500 }],
      quest_points: 2,
    },
  },
  {
    id: Id('Elemental-Workshop-I'),
    name: Name('Elemental Workshop I'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Elemental_Workshop_I',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Elemental Workshop',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Mining), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Smithing), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 20, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 5000 },
        { skill: Skill(SkillEnum.Smithing), amount: 5000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Elemental-Workshop-II'),
    name: Name('Elemental Workshop II'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Elemental_Workshop_II',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Elemental Workshop (#2)',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Magic), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Smithing), level: 30, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 7500 },
        { skill: Skill(SkillEnum.Smithing), amount: 7500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Enakhras-Lament'),
    name: Name("Enakhra's Lament"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Enakhra%27s_Lament',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Mahjarrat',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 50, boostable: false },
        { skill: Skill(SkillEnum.Firemaking), level: 45, boostable: false },
        { skill: Skill(SkillEnum.Prayer), level: 43, boostable: false },
        { skill: Skill(SkillEnum.Magic), level: 39, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 45, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 7000 },
        { skill: Skill(SkillEnum.Firemaking), amount: 7000 },
        { skill: Skill(SkillEnum.Magic), amount: 7000 },
        { skill: Skill(SkillEnum.Mining), amount: 7000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Enlightened-Journey'),
    name: Name('Enlightened Journey'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Enlightened_Journey',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Long',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Quest_points), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Firemaking), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Farming), level: 30, boostable: true },
        { skill: Skill(SkillEnum.Crafting), level: 36, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 2000 },
        { skill: Skill(SkillEnum.Farming), amount: 3000 },
        { skill: Skill(SkillEnum.Firemaking), amount: 4000 },
        { skill: Skill(SkillEnum.Woodcutting), amount: 1500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Enter-the-Abyss'),
    name: Name('Enter the Abyss'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Enter_the_Abyss',
    is_members_only: true,
    is_miniquest: true,
    difficulty: 'Novice',
    length: 'Short â€“ Long',
    series: null,
    requirements: { quests: ['Rune Mysteries'], levels: [] },
    rewards: { experience: [], quest_points: 0 },
  },
  {
    id: Id('Ernest-the-Chicken'),
    name: Name('Ernest the Chicken'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Ernest_the_Chicken',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 4 },
  },
  {
    id: Id('Fairytale-I---Growing-Pains'),
    name: Name('Fairytale I - Growing Pains'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Fairytale_I_-_Growing_Pains',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Fairy Tale (#2)',
    requirements: { quests: ['Lost City', 'Nature Spirit'], levels: [] },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Attack), amount: 2000 },
        { skill: Skill(SkillEnum.Farming), amount: 3500 },
        { skill: Skill(SkillEnum.Magic), amount: 1000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Fairytale-II---Cure-a-Queen'),
    name: Name('Fairytale II - Cure a Queen'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Fairytale_II_-_Cure_a_Queen',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short - Medium',
    series: 'Fairy Tale (#2)',
    requirements: {
      quests: ['Fairytale I - Growing Pains'],
      levels: [
        { skill: Skill(SkillEnum.Thieving), level: 40, boostable: true },
        { skill: Skill(SkillEnum.Farming), level: 49, boostable: true },
        { skill: Skill(SkillEnum.Herblore), level: 57, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Herblore), amount: 3500 },
        { skill: Skill(SkillEnum.Thieving), amount: 2500 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Family-Crest'),
    name: Name('Family Crest'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Family_Crest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Mining), level: 40, boostable: true },
        { skill: Skill(SkillEnum.Smithing), level: 40, boostable: true },
        { skill: Skill(SkillEnum.Magic), level: 59, boostable: true },
        { skill: Skill(SkillEnum.Crafting), level: 40, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: Id('Fight-Arena'),
    name: Name('Fight Arena'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Fight_Arena',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short',
    series: 'Mahjarrat',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Attack), amount: 12175 },
        { skill: Skill(SkillEnum.Thieving), amount: 2175 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Fishing-Contest'),
    name: Name('Fishing Contest'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Fishing_Contest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Dwarf',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Fishing), level: 10, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Fishing), amount: 2437 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Forgettable-Tale'),
    name: Name('Forgettable Tale...'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Forgettable_Tale...',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Rise of the Red Axe',
    requirements: {
      quests: ['The Giant Dwarf', 'Fishing Contest'],
      levels: [
        { skill: Skill(SkillEnum.Cooking), level: 22, boostable: false },
        { skill: Skill(SkillEnum.Farming), level: 17, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Cooking), amount: 5000 },
        { skill: Skill(SkillEnum.Farming), amount: 5000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Garden-of-Tranquillity'),
    name: Name('Garden of Tranquillity'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Garden_of_Tranquillity',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Very long',
    series: null,
    requirements: {
      quests: ['Creature of Fenkenstrain'],
      levels: [
        { skill: Skill(SkillEnum.Farming), level: 25, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Farming), amount: 5000 }],
      quest_points: 2,
    },
  },
  {
    id: Id('Gertrudes-Cat'),
    name: Name("Gertrude's Cat"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Gertrude%27s_Cat',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Cooking), amount: 1525 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Ghosts-Ahoy'),
    name: Name('Ghosts Ahoy'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Ghosts_Ahoy',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Prayer), amount: 2400 }],
      quest_points: 2,
    },
  },
  {
    id: Id('Goblin-Diplomacy'),
    name: Name('Goblin Diplomacy'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Goblin_Diplomacy',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Crafting), amount: 200 }],
      quest_points: 5,
    },
  },
  {
    id: Id('Grim-Tales'),
    name: Name('Grim Tales'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Grim_Tales',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Farming), level: 45, boostable: true },
        { skill: Skill(SkillEnum.Herblore), level: 52, boostable: true },
        { skill: Skill(SkillEnum.Thieving), level: 58, boostable: true },
        { skill: Skill(SkillEnum.Agility), level: 59, boostable: true },
        { skill: Skill(SkillEnum.Woodcutting), level: 71, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 6000 },
        { skill: Skill(SkillEnum.Farming), amount: 4000 },
        { skill: Skill(SkillEnum.Herblore), amount: 5000 },
        { skill: Skill(SkillEnum.Hitpoints), amount: 5000 },
        { skill: Skill(SkillEnum.Thieving), amount: 6000 },
        { skill: Skill(SkillEnum.Woodcutting), amount: 14000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Haunted-Mine'),
    name: Name('Haunted Mine'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Haunted_Mine',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium - Long',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 15, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 35, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Strength), amount: 22000 }],
      quest_points: 2,
    },
  },
  {
    id: Id('Hazeel-Cult'),
    name: Name('Hazeel Cult'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Hazeel_Cult',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Mahjarrat',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Thieving), amount: 1500 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Heroes-Quest'),
    name: Name("Heroes' Quest"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Heroes%27_Quest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium - Long',
    series: 'Guild',
    requirements: {
      quests: [
        'Shield of Arrav',
        'Lost City',
        "Merlin's Crystal",
        'Dragon Slayer',
        'Druidic Ritual',
      ],
      levels: [
        { skill: Skill(SkillEnum.Quest_points), level: 55, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Attack), amount: 3075 },
        { skill: Skill(SkillEnum.Cooking), amount: 2825 },
        { skill: Skill(SkillEnum.Defence), amount: 3075 },
        { skill: Skill(SkillEnum.Firemaking), amount: 1575 },
        { skill: Skill(SkillEnum.Fishing), amount: 2725 },
        { skill: Skill(SkillEnum.Herblore), amount: 1325 },
        { skill: Skill(SkillEnum.Hitpoints), amount: 3075 },
        { skill: Skill(SkillEnum.Mining), amount: 2575 },
        { skill: Skill(SkillEnum.Ranged), amount: 2075 },
        { skill: Skill(SkillEnum.Smithing), amount: 2257 },
        { skill: Skill(SkillEnum.Strength), amount: 3075 },
        { skill: Skill(SkillEnum.Woodcutting), amount: 1575 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Holy-Grail'),
    name: Name('Holy Grail'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Holy_Grail',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Camelot (#2)',
    requirements: {
      quests: [],
      levels: [{ skill: Skill(SkillEnum.Attack), level: 20, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Defence), amount: 15300 },
        { skill: Skill(SkillEnum.Prayer), amount: 11000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Horror-from-the-Deep'),
    name: Name('Horror from the Deep'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Horror_from_the_Deep',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [{ skill: Skill(SkillEnum.Agility), level: 35, boostable: true }],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Magic), amount: 4662 },
        { skill: Skill(SkillEnum.Ranged), amount: 4662.5 },
        { skill: Skill(SkillEnum.Strength), amount: 4662.5 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Icthlarins-Little-Helper'),
    name: Name("Icthlarin's Little Helper"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Icthlarin%27s_Little_Helper',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: 'Desert',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 4000 },
        { skill: Skill(SkillEnum.Thieving), amount: 4500 },
        { skill: Skill(SkillEnum.Woodcutting), amount: 4000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Imp-Catcher'),
    name: Name('Imp Catcher'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Imp_Catcher',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short (<5-15 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Magic), amount: 875 }],
      quest_points: 1,
    },
  },
  {
    id: Id('In-Aid-of-the-Myreque'),
    name: Name('In Aid of the Myreque'),
    wiki_url: 'https://oldschool.runescape.wiki/w/In_Aid_of_the_Myreque',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Myreque',
    requirements: {
      quests: ['In Search of the Myreque'],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 25, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 15, boostable: false },
        { skill: Skill(SkillEnum.Magic), level: 7, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Attack), amount: 2000 },
        { skill: Skill(SkillEnum.Crafting), amount: 2000 },
        { skill: Skill(SkillEnum.Defence), amount: 2000 },
        { skill: Skill(SkillEnum.Strength), amount: 2000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('In-Search-of-the-Myreque'),
    name: Name('In Search of the Myreque'),
    wiki_url: 'https://oldschool.runescape.wiki/w/In_Search_of_the_Myreque',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: 'Myreque',
    requirements: {
      quests: ['Nature Spirit'],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 25, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Attack), amount: 600 },
        { skill: Skill(SkillEnum.Crafting), amount: 600 },
        { skill: Skill(SkillEnum.Defence), amount: 600 },
        { skill: Skill(SkillEnum.Hitpoints), amount: 600 },
        { skill: Skill(SkillEnum.Strength), amount: 600 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Jungle-Potion'),
    name: Name('Jungle Potion'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Jungle_Potion',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short - Medium',
    series: 'Karamja',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Herblore), level: 3, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Herblore), amount: 775 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Kings-Ransom'),
    name: Name("King's Ransom"),
    wiki_url: 'https://oldschool.runescape.wiki/w/King%27s_Ransom',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Camelot (#3)',
    requirements: {
      quests: [
        "Black Knights' Fortress",
        'Holy Grail',
        'Murder Mystery',
        'One Small Favour',
      ],
      levels: [
        { skill: Skill(SkillEnum.Magic), level: 45, boostable: false },
        { skill: Skill(SkillEnum.Defence), level: 65, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Defence), amount: 33000 },
        { skill: Skill(SkillEnum.Magic), amount: 5000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Legends-Quest'),
    name: Name("Legends' Quest"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Legends%27_Quest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Very long',
    series: 'Karamja, Guild',
    requirements: {
      quests: [
        'Family Crest',
        "Heroes' Quest",
        'Shilo Village',
        'Underground Pass',
        'Waterfall Quest',
      ],
      levels: [
        { skill: Skill(SkillEnum.Quest_points), level: 107, boostable: false },
        { skill: Skill(SkillEnum.Agility), level: 50, boostable: true },
        { skill: Skill(SkillEnum.Crafting), level: 50, boostable: false },
        { skill: Skill(SkillEnum.Herblore), level: 45, boostable: true },
        { skill: Skill(SkillEnum.Magic), level: 56, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 52, boostable: true },
        { skill: Skill(SkillEnum.Prayer), level: 42, boostable: true },
        { skill: Skill(SkillEnum.Smithing), level: 50, boostable: true },
        { skill: Skill(SkillEnum.Strength), level: 50, boostable: true },
        { skill: Skill(SkillEnum.Thieving), level: 50, boostable: false },
        { skill: Skill(SkillEnum.Woodcutting), level: 50, boostable: true },
      ],
    },
    rewards: { experience: [], quest_points: 4 },
  },
  {
    id: Id('Lost-City'),
    name: Name('Lost City'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Lost_City',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short',
    series: 'Fairy Tale',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 31, boostable: false },
        { skill: Skill(SkillEnum.Woodcutting), level: 36, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 3 },
  },
  {
    id: Id('Lunar-Diplomacy'),
    name: Name('Lunar Diplomacy'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Lunar_Diplomacy',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Fremennik',
    requirements: {
      quests: [
        'The Fremennik Trials',
        'Lost City',
        'Rune Mysteries',
        'Shilo Village',
      ],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 61, boostable: false },
        { skill: Skill(SkillEnum.Defence), level: 40, boostable: false },
        { skill: Skill(SkillEnum.Firemaking), level: 49, boostable: false },
        { skill: Skill(SkillEnum.Magic), level: 65, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 60, boostable: false },
        { skill: Skill(SkillEnum.Woodcutting), level: 55, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Magic), amount: 5000 },
        { skill: Skill(SkillEnum.Runecraft), amount: 5000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Making-Friends-with-My-Arm'),
    name: Name('Making Friends with My Arm'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Making_Friends_with_My_Arm',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Medium',
    series: 'Troll',
    requirements: {
      quests: [
        "My Arm's Big Adventure",
        'Swan Song',
        'Cold War',
        'Romeo & Juliet',
      ],
      levels: [
        { skill: Skill(SkillEnum.Firemaking), level: 66, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 72, boostable: false },
        { skill: Skill(SkillEnum.Construction), level: 35, boostable: false },
        { skill: Skill(SkillEnum.Agility), level: 68, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 10000 },
        { skill: Skill(SkillEnum.Construction), amount: 2000 },
        { skill: Skill(SkillEnum.Firemaking), amount: 5000 },
        { skill: Skill(SkillEnum.Mining), amount: 10000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Making-History'),
    name: Name('Making History'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Making_History',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Long',
    series: 'Enchanted Key',
    requirements: {
      quests: ['Priest in Peril', 'The Restless Ghost'],
      levels: [],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 1000 },
        { skill: Skill(SkillEnum.Prayer), amount: 1000 },
      ],
      quest_points: 3,
    },
  },
  {
    id: Id('Merlins-Crystal'),
    name: Name("Merlin's Crystal"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Merlin%27s_Crystal',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium-Long (Under 10 minutes with teleports)',
    series: 'Camelot',
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 6 },
  },
  {
    id: Id('Misthalin-Mystery'),
    name: Name('Misthalin Mystery'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Misthalin_Mystery',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Crafting), amount: 600 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Monks-Friend'),
    name: Name("Monk's Friend"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Monk%27s_Friend',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Very Short (5 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Woodcutting), amount: 2000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Monkey-Madness-I'),
    name: Name('Monkey Madness I'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Monkey_Madness_I',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Long',
    series: 'Gnome, Monkey',
    requirements: {
      quests: ['The Grand Tree', 'Tree Gnome Village'],
      levels: [{ skill: Skill(SkillEnum.Prayer), level: 43, boostable: false }],
    },
    rewards: { experience: [], quest_points: 3 },
  },
  {
    id: Id('Monkey-Madness-II'),
    name: Name('Monkey Madness II'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Monkey_Madness_II',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Grandmaster',
    length: 'Very long',
    series: 'Gnome, Monkey',
    requirements: {
      quests: [
        'Enlightened Journey',
        'The Eyes of Glouphrie',
        'Recipe for Disaster',
        'Troll Stronghold',
        'Watchtower',
      ],
      levels: [
        { skill: Skill(SkillEnum.Slayer), level: 69, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 70, boostable: false },
        { skill: Skill(SkillEnum.Hunter), level: 60, boostable: false },
        { skill: Skill(SkillEnum.Agility), level: 55, boostable: false },
        { skill: Skill(SkillEnum.Thieving), level: 55, boostable: false },
        { skill: Skill(SkillEnum.Firemaking), level: 60, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 20000 },
        { skill: Skill(SkillEnum.Hunter), amount: 15000 },
        { skill: Skill(SkillEnum.Slayer), amount: 25000 },
        { skill: Skill(SkillEnum.Thieving), amount: 15000 },
      ],
      quest_points: 4,
    },
  },
  {
    id: Id('Mountain-Daughter'),
    name: Name('Mountain Daughter'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Mountain_Daughter',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 20, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Attack), amount: 1000 },
        { skill: Skill(SkillEnum.Prayer), amount: 2000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Mournings-End-Part-I'),
    name: Name("Mourning's End Part I"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Mourning%27s_Ends_Part_I',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Short',
    series: 'Elf',
    requirements: {
      quests: ['Roving Elves', 'Big Chompy Bird Hunting', 'Sheep Herder'],
      levels: [
        { skill: Skill(SkillEnum.Ranged), level: 60, boostable: true },
        { skill: Skill(SkillEnum.Thieving), level: 50, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Hitpoints), amount: 25000 },
        { skill: Skill(SkillEnum.Thieving), amount: 25000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Mournings-End-Part-II'),
    name: Name("Mourning's End Part II"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Mourning%27s_Ends_Part_II',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Short',
    series: 'Elf',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Prayer), level: 43, boostable: false },
        { skill: Skill(SkillEnum.Agility), level: 60, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Agility), amount: 20000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Murder-Mystery'),
    name: Name('Murder Mystery'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Murder_Mystery',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Camelot',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Crafting), amount: 1406 }],
      quest_points: 3,
    },
  },
  {
    id: Id('My-Arms-Big-Adventure'),
    name: Name("My Arm's Big Adventure"),
    wiki_url: 'https://oldschool.runescape.wiki/w/My_Arm%27s_Big_Adventure',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Troll',
    requirements: {
      quests: ["Eadgar's Ruse", 'The Feud', 'Jungle Potion'],
      levels: [
        { skill: Skill(SkillEnum.Woodcutting), level: 10, boostable: false },
        { skill: Skill(SkillEnum.Farming), level: 29, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Farming), amount: 5000 },
        { skill: Skill(SkillEnum.Herblore), amount: 10000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Nature-Spirit'),
    name: Name('Nature Spirit'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Nature_Spirit',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Myreque',
    requirements: {
      quests: ['Priest in Peril', 'The Restless Ghost'],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 18, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 3000 },
        { skill: Skill(SkillEnum.Defence), amount: 2000 },
        { skill: Skill(SkillEnum.Hitpoints), amount: 2000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Observatory-Quest'),
    name: Name('Observatory Quest'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Observatory_Quest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short - Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 10, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Crafting), amount: 2250 }],
      quest_points: 2,
    },
  },
  {
    id: Id('Olafs-Quest'),
    name: Name("Olaf's Quest"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Olaf%27s_Quest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Long',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Firemaking), level: 40, boostable: false },
        { skill: Skill(SkillEnum.Woodcutting), level: 50, boostable: true },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Defence), amount: 12000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('One-Small-Favour'),
    name: Name('One Small Favour'),
    wiki_url: 'https://oldschool.runescape.wiki/w/One_Small_Favour',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Very long',
    series: 'Karamja',
    requirements: {
      quests: ['Rune Mysteries', 'Shilo Village'],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 36, boostable: true },
        { skill: Skill(SkillEnum.Crafting), level: 25, boostable: false },
        { skill: Skill(SkillEnum.Herblore), level: 18, boostable: false },
        { skill: Skill(SkillEnum.Smithing), level: 30, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 2 },
  },
  {
    id: Id('Pirates-Treasure'),
    name: Name("Pirate's Treasure"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Pirate%27s_Treasure',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Pirate',
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 2 },
  },
  {
    id: Id('Plague-City'),
    name: Name('Plague City'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Plague_City',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Elf',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Mining), amount: 2425 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Priest-in-Peril'),
    name: Name('Priest in Peril'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Priest_in_Peril',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Myreque',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Prayer), amount: 1406 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Prince-Ali-Rescue'),
    name: Name('Prince Ali Rescue'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Prince_Ali_Rescue',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 3 },
  },
  {
    id: Id('Rag-and-Bone-Man'),
    name: Name('Rag and Bone Man'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Rag_and_Bone_Man',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Cooking), amount: 500 },
        { skill: Skill(SkillEnum.Prayer), amount: 500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Rag-and-Bone-Man-II'),
    name: Name('Rag and Bone Man II'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Rag_and_Bone_Man_II',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Slayer), level: 40, boostable: false },
        { skill: Skill(SkillEnum.Defence), level: 20, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Prayer), amount: 5000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Ratcatchers'),
    name: Name('Ratcatchers'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Ratcatchers',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long - Very long',
    series: null,
    requirements: { quests: ["Icthlarin's Little Helper"], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Thieving), amount: 4500 }],
      quest_points: 2,
    },
  },
  {
    id: Id('Recipe-for-Disaster'),
    name: Name('Recipe for Disaster'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Recipe_for_Disaster',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Special',
    length: 'Very long',
    series: null,
    requirements: {
      quests: [
        "Cook's Assistant",
        'Fishing Contest',
        'Goblin Diplomacy',
        'Big Chompy Bird Hunting',
        'Murder Mystery',
        'Nature Spirit',
        "Witch's House",
        "Gertrude's Cat",
        'Shadow of the Storm',
        "Started Legends' Quest",
        'Monkey Madness I',
        'Desert Treasure',
        'Horror from the Deep',
      ],
      levels: [
        { skill: Skill(SkillEnum.Quest_points), level: 175, boostable: false },
        { skill: Skill(SkillEnum.Cooking), level: 70, boostable: true },
        { skill: Skill(SkillEnum.Agility), level: 48, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 50, boostable: true },
        { skill: Skill(SkillEnum.Fishing), level: 53, boostable: true },
        { skill: Skill(SkillEnum.Thieving), level: 53, boostable: false },
        { skill: Skill(SkillEnum.Herblore), level: 25, boostable: true },
        { skill: Skill(SkillEnum.Magic), level: 59, boostable: true },
        { skill: Skill(SkillEnum.Smithing), level: 40, boostable: false },
        { skill: Skill(SkillEnum.Firemaking), level: 50, boostable: false },
        { skill: Skill(SkillEnum.Ranged), level: 40, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 40, boostable: false },
        { skill: Skill(SkillEnum.Fletching), level: 10, boostable: false },
        { skill: Skill(SkillEnum.Slayer), level: 10, boostable: false },
        { skill: Skill(SkillEnum.Woodcutting), level: 36, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 10 },
  },
  {
    id: Id('Recruitment-Drive'),
    name: Name('Recruitment Drive'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Recruitment_Drive',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Temple Knight',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Quest_points), level: 12, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 1000 },
        { skill: Skill(SkillEnum.Herblore), amount: 1000 },
        { skill: Skill(SkillEnum.Prayer), amount: 1000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Regicide'),
    name: Name('Regicide'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Regicide',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Long',
    series: 'Elf',
    requirements: {
      quests: ['Underground Pass'],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 56, boostable: true },
        { skill: Skill(SkillEnum.Crafting), level: 10, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Agility), amount: 13750 }],
      quest_points: 3,
    },
  },
  {
    id: Id('Romeo--Juliet'),
    name: Name('Romeo & Juliet'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Romeo_%26_Juliet',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 5 },
  },
  {
    id: Id('Roving-Elves'),
    name: Name('Roving Elves'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Roving_Elves',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Short - Medium',
    series: 'Elf, Gnome',
    requirements: { quests: ['Regicide', 'Waterfall Quest'], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Strength), amount: 10000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Royal-Trouble'),
    name: Name('Royal Trouble'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Royal_Trouble',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 40, boostable: true },
        { skill: Skill(SkillEnum.Slayer), level: 40, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 5000 },
        { skill: Skill(SkillEnum.Hitpoints), amount: 5000 },
        { skill: Skill(SkillEnum.Slayer), amount: 5000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Rum-Deal'),
    name: Name('Rum Deal'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Rum_Deal',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Pirate',
    requirements: {
      quests: ['Zogre Flesh Eaters', 'Priest in Peril'],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 42, boostable: false },
        { skill: Skill(SkillEnum.Fishing), level: 50, boostable: true },
        { skill: Skill(SkillEnum.Farming), level: 40, boostable: true },
        { skill: Skill(SkillEnum.Prayer), level: 47, boostable: true },
        { skill: Skill(SkillEnum.Slayer), level: 42, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Farming), amount: 7000 },
        { skill: Skill(SkillEnum.Fishing), amount: 7000 },
        { skill: Skill(SkillEnum.Prayer), amount: 7000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Rune-Mysteries'),
    name: Name('Rune Mysteries'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Rune_Mysteries',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short (<5 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: Id('Scorpion-Catcher'),
    name: Name('Scorpion Catcher'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Scorpion_Catcher',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: Skill(SkillEnum.Prayer), level: 31, boostable: false }],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Strength), amount: 6625 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Sea-Slug'),
    name: Name('Sea Slug'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Sea_Slug',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: 'Sea Slug',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Fishing), amount: 7175 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Shades-of-Mortton'),
    name: Name("Shades of Mort'ton"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Shades_of_Mort%27ton',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: "Mort'ton",
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Herblore), level: 15, boostable: false },
        { skill: Skill(SkillEnum.Firemaking), level: 5, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 2000 },
        { skill: Skill(SkillEnum.Herblore), amount: 2000 },
      ],
      quest_points: 3,
    },
  },
  {
    id: Id('Shadow-of-the-Storm'),
    name: Name('Shadow of the Storm'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Shadow_of_the_Storm',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: null,
    requirements: { quests: ['The Golem', 'Demon Slayer'], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: Id('Sheep-Herder'),
    name: Name('Sheep Herder'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Sheep_Herder',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short/Medium',
    series: 'Plague/Elf',
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 4 },
  },
  {
    id: Id('Sheep-Shearer'),
    name: Name('Sheep Shearer'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Sheep_Shearer',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Crafting), amount: 150 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Shield-of-Arrav'),
    name: Name('Shield of Arrav'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Shield_of_Arrav',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Mahjarrat',
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: Id('Shilo-Village'),
    name: Name('Shilo Village'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Shilo_Village',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium - Long',
    series: 'Karamja',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Agility), level: 32, boostable: true },
        { skill: Skill(SkillEnum.Smithing), level: 4, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Crafting), amount: 3875 }],
      quest_points: 2,
    },
  },
  {
    id: Id('Song-of-the-Elves'),
    name: Name('Song of the Elves'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Song_of_the_Elves',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Grandmaster',
    length: 'Very long',
    series: 'Elf',
    requirements: {
      quests: ["Mourning's End Part II", 'Making History'],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 70, boostable: false },
        { skill: Skill(SkillEnum.Construction), level: 70, boostable: false },
        { skill: Skill(SkillEnum.Farming), level: 70, boostable: false },
        { skill: Skill(SkillEnum.Herblore), level: 70, boostable: false },
        { skill: Skill(SkillEnum.Hunter), level: 70, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 70, boostable: false },
        { skill: Skill(SkillEnum.Smithing), level: 70, boostable: false },
        { skill: Skill(SkillEnum.Woodcutting), level: 70, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 20000 },
        { skill: Skill(SkillEnum.Construction), amount: 20000 },
        { skill: Skill(SkillEnum.Farming), amount: 20000 },
        { skill: Skill(SkillEnum.Herblore), amount: 20000 },
        { skill: Skill(SkillEnum.Hunter), amount: 20000 },
        { skill: Skill(SkillEnum.Mining), amount: 20000 },
        { skill: Skill(SkillEnum.Smithing), amount: 20000 },
        { skill: Skill(SkillEnum.Woodcutting), amount: 20000 },
      ],
      quest_points: 4,
    },
  },
  {
    id: Id('Spirits-of-the-Elid'),
    name: Name('Spirits of the Elid'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Spirits_of_the_Elid',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Desert',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Magic), level: 33, boostable: true },
        { skill: Skill(SkillEnum.Ranged), level: 37, boostable: true },
        { skill: Skill(SkillEnum.Mining), level: 37, boostable: false },
        { skill: Skill(SkillEnum.Thieving), level: 37, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Magic), amount: 1000 },
        { skill: Skill(SkillEnum.Prayer), amount: 8000 },
        { skill: Skill(SkillEnum.Thieving), amount: 1000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Swan-Song'),
    name: Name('Swan Song'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Swan_Song',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Medium',
    series: 'Wise Old Man',
    requirements: {
      quests: ['One Small Favour', 'Garden of Tranquillity'],
      levels: [
        { skill: Skill(SkillEnum.Quest_points), level: 100, boostable: false },
        { skill: Skill(SkillEnum.Magic), level: 66, boostable: true },
        { skill: Skill(SkillEnum.Cooking), level: 62, boostable: true },
        { skill: Skill(SkillEnum.Fishing), level: 62, boostable: true },
        { skill: Skill(SkillEnum.Smithing), level: 45, boostable: true },
        { skill: Skill(SkillEnum.Firemaking), level: 42, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 40, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Fishing), amount: 10000 },
        { skill: Skill(SkillEnum.Magic), amount: 15000 },
        { skill: Skill(SkillEnum.Prayer), amount: 10000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Tai-Bwo-Wannai-Trio'),
    name: Name('Tai Bwo Wannai Trio'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Tai_Bwo_Wannai_Trio',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Karamja',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 15, boostable: false },
        { skill: Skill(SkillEnum.Cooking), level: 30, boostable: false },
        { skill: Skill(SkillEnum.Fishing), level: 5, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Attack), amount: 2500 },
        { skill: Skill(SkillEnum.Cooking), amount: 5000 },
        { skill: Skill(SkillEnum.Fishing), amount: 5000 },
        { skill: Skill(SkillEnum.Strength), amount: 2500 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Tale-of-the-Righteous'),
    name: Name('Tale of the Righteous'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Tale_of_the_Righteous',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Great Kourend',
    requirements: {
      quests: ['Client of Kourend'],
      levels: [
        { skill: Skill(SkillEnum.Strength), level: 16, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 10, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: Id('Tears-of-Guthix'),
    name: Name('Tears of Guthix'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Tears_of_Guthix_(quest)',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Short',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Quest_points), level: 43, boostable: false },
        { skill: Skill(SkillEnum.Firemaking), level: 49, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 20, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Crafting), amount: 1000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Temple-of-Ikov'),
    name: Name('Temple of Ikov'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Temple_of_Ikov',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Mahjarrat',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Thieving), level: 42, boostable: true },
        { skill: Skill(SkillEnum.Ranged), level: 40, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Fletching), amount: 8000 },
        { skill: Skill(SkillEnum.Ranged), amount: 10500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Ascent-of-Arceuus'),
    name: Name('The Ascent of Arceuus'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Ascent_of_Arceuus',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Great Kourend',
    requirements: {
      quests: ['Client of Kourend'],
      levels: [{ skill: Skill(SkillEnum.Hunter), level: 12, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Hunter), amount: 1500 },
        { skill: Skill(SkillEnum.Runecraft), amount: 500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Corsair-Curse'),
    name: Name('The Corsair Curse'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Corsair_Curse',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 2 },
  },
  {
    id: Id('The-Depths-of-Despair'),
    name: Name('The Depths of Despair'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Depths_of_Despair',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Great Kourend',
    requirements: {
      quests: ['Client of Kourend'],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 18, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Agility), amount: 1500 }],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Dig-Site'),
    name: Name('The Dig Site'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Dig_Site',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'The Return of Zaros',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 10, boostable: false },
        { skill: Skill(SkillEnum.Herblore), level: 10, boostable: false },
        { skill: Skill(SkillEnum.Thieving), level: 25, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Herblore), amount: 2000 },
        { skill: Skill(SkillEnum.Mining), amount: 15300 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('The-Eyes-of-Glouphrie'),
    name: Name('The Eyes of Glouphrie'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Eyes_of_Glouphrie',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: 'Gnome',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Construction), level: 5, boostable: false },
        { skill: Skill(SkillEnum.Magic), level: 46, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Construction), amount: 250 },
        { skill: Skill(SkillEnum.Magic), amount: 12000 },
        { skill: Skill(SkillEnum.Runecraft), amount: 6000 },
        { skill: Skill(SkillEnum.Woodcutting), amount: 2500 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('The-Feud'),
    name: Name('The Feud'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Feud',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Desert',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Thieving), level: 30, boostable: true },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Thieving), amount: 15000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Forsaken-Tower'),
    name: Name('The Forsaken Tower'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Forsaken_Tower',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Great Kourend',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Mining), amount: 500 },
        { skill: Skill(SkillEnum.Smithing), amount: 500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Fremennik-Exiles'),
    name: Name('The Fremennik Exiles'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Fremennik_Exiles',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Medium',
    series: 'Fremennik',
    requirements: {
      quests: [
        'The Fremennik Isles',
        'Lunar Diplomacy',
        'Mountain Daughter',
        "Heroes' Quest",
      ],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 65, boostable: false },
        { skill: Skill(SkillEnum.Slayer), level: 60, boostable: false },
        { skill: Skill(SkillEnum.Smithing), level: 60, boostable: false },
        { skill: Skill(SkillEnum.Fishing), level: 60, boostable: false },
        { skill: Skill(SkillEnum.Runecraft), level: 55, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 15000 },
        { skill: Skill(SkillEnum.Runecraft), amount: 5000 },
        { skill: Skill(SkillEnum.Slayer), amount: 15000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('The-Fremennik-Isles'),
    name: Name('The Fremennik Isles'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Fremennik_Isles',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Construction), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Agility), level: 40, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Construction), amount: 5000 },
        { skill: Skill(SkillEnum.Crafting), amount: 5000 },
        { skill: Skill(SkillEnum.Woodcutting), amount: 10000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Fremennik-Trials'),
    name: Name('The Fremennik Trials'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Fremennik_Trials',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Fremennik',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 2812 },
        { skill: Skill(SkillEnum.Attack), amount: 2812 },
        { skill: Skill(SkillEnum.Crafting), amount: 2812 },
        { skill: Skill(SkillEnum.Defence), amount: 2812 },
        { skill: Skill(SkillEnum.Fishing), amount: 2812 },
        { skill: Skill(SkillEnum.Fletching), amount: 2812 },
        { skill: Skill(SkillEnum.Hitpoints), amount: 2812 },
        { skill: Skill(SkillEnum.Strength), amount: 2812 },
        { skill: Skill(SkillEnum.Thieving), amount: 2812 },
        { skill: Skill(SkillEnum.Woodcutting), amount: 2812 },
      ],
      quest_points: 3,
    },
  },
  {
    id: Id('The-Giant-Dwarf'),
    name: Name('The Giant Dwarf'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Giant_Dwarf',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: 'Rise of the Red Axe',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 12, boostable: false },
        { skill: Skill(SkillEnum.Firemaking), level: 16, boostable: false },
        { skill: Skill(SkillEnum.Magic), level: 33, boostable: false },
        { skill: Skill(SkillEnum.Thieving), level: 14, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Smithing), level: 20, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 2500 },
        { skill: Skill(SkillEnum.Firemaking), amount: 1500 },
        { skill: Skill(SkillEnum.Magic), amount: 1500 },
        { skill: Skill(SkillEnum.Mining), amount: 2500 },
        { skill: Skill(SkillEnum.Smithing), amount: 2500 },
        { skill: Skill(SkillEnum.Thieving), amount: 1500 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('The-Golem'),
    name: Name('The Golem'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Golem',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 20, boostable: false },
        { skill: Skill(SkillEnum.Thieving), level: 25, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 1000 },
        { skill: Skill(SkillEnum.Thieving), amount: 1000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Grand-Tree'),
    name: Name('The Grand Tree'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Grand_Tree',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Gnome',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 25, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 7900 },
        { skill: Skill(SkillEnum.Attack), amount: 18400 },
        { skill: Skill(SkillEnum.Magic), amount: 2150 },
      ],
      quest_points: 5,
    },
  },
  {
    id: Id('The-Great-Brain-Robbery'),
    name: Name('The Great Brain Robbery'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Great_Brain_Robbery',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Pirate',
    requirements: {
      quests: [
        'Creature of Fenkenstrain',
        'Cabin Fever',
        'Pirate Pete subquest of Recipe for Disaster',
      ],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 16, boostable: false },
        { skill: Skill(SkillEnum.Construction), level: 30, boostable: false },
        { skill: Skill(SkillEnum.Prayer), level: 50, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Construction), amount: 2000 },
        { skill: Skill(SkillEnum.Crafting), amount: 3000 },
        { skill: Skill(SkillEnum.Prayer), amount: 6000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('The-Hand-in-the-Sand'),
    name: Name('The Hand in the Sand'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Hand_in_the_Sand',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 9000 },
        { skill: Skill(SkillEnum.Thieving), amount: 1000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Knights-Sword'),
    name: Name("The Knight's Sword"),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Knight%27s_Sword',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: Skill(SkillEnum.Mining), level: 10, boostable: false }],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Smithing), amount: 12725 }],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Lost-Tribe'),
    name: Name('The Lost Tribe'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Lost_Tribe',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Dorgeshuun',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 13, boostable: false },
        { skill: Skill(SkillEnum.Thieving), level: 13, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 17, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Mining), amount: 3000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Queen-of-Thieves'),
    name: Name('The Queen of Thieves'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Queen_of_Thieves',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Great Kourend',
    requirements: {
      quests: ['Client of Kourend'],
      levels: [
        { skill: Skill(SkillEnum.Thieving), level: 20, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Thieving), amount: 2000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Restless-Ghost'),
    name: Name('The Restless Ghost'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Restless_Ghost',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short (<10 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Prayer), amount: 1125 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Sins-of-the-Father'),
    name: Name('Sins of the Father'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Sins_of_the_Father',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Long',
    series: null,
    requirements: {
      quests: [
        'Vampyre Slayer',
        'A Taste of Hope',
        'Darkness of Hallowvale',
        'In Aid of the Myreque',
        'In Search of the Myreque',
        'Nature Spirit',
        'Priest in Peril',
        'The Restless Ghost',
      ],
      levels: [
        { skill: Skill(SkillEnum.Woodcutting), level: 62, boostable: false },
        { skill: Skill(SkillEnum.Fletching), level: 60, boostable: false },
        { skill: Skill(SkillEnum.Crafting), level: 56, boostable: false },
        { skill: Skill(SkillEnum.Agility), level: 52, boostable: false },
        { skill: Skill(SkillEnum.Attack), level: 50, boostable: false },
        { skill: Skill(SkillEnum.Slayer), level: 50, boostable: false },
        { skill: Skill(SkillEnum.Magic), level: 49, boostable: false },
      ],
    },
    rewards: {
      experience: [],
      quest_points: 2,
      items: ['Blisterwood flail'],
      other: [
        'Access to Darkmeyer',
        'A tome of experience, granting 15,000 experience to any three skills (level 60 or higher). Can be the same skill.',
        "Darkmeyer teleport via Drakan's medallion",
        'Boat travel between Burgh de Rott, Slepe and the Icyene Graveyard',
      ],
    },
  },
  {
    id: Id('The-Slug-Menace'),
    name: Name('The Slug Menace'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Slug_Menace',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: 'Sea Slug',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Crafting), level: 30, boostable: false },
        { skill: Skill(SkillEnum.Runecraft), level: 30, boostable: true },
        { skill: Skill(SkillEnum.Slayer), level: 30, boostable: true },
        { skill: Skill(SkillEnum.Thieving), level: 30, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Crafting), amount: 3500 },
        { skill: Skill(SkillEnum.Runecraft), amount: 3500 },
        { skill: Skill(SkillEnum.Thieving), amount: 3500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('The-Tourist-Trap'),
    name: Name('The Tourist Trap'),
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Tourist_Trap',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Desert',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Fletching), level: 10, boostable: false },
        { skill: Skill(SkillEnum.Smithing), level: 20, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 2 },
  },
  {
    id: Id('Throne-of-Miscellania'),
    name: Name('Throne of Miscellania'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Throne_of_Miscellania',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Woodcutting), level: 45, boostable: false },
        { skill: Skill(SkillEnum.Farming), level: 10, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 30, boostable: false },
        { skill: Skill(SkillEnum.Fishing), level: 35, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: Id('Tower-of-Life'),
    name: Name('Tower of Life'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Tower_of_Life',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Construction), level: 10, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Construction), amount: 1000 },
        { skill: Skill(SkillEnum.Crafting), amount: 500 },
        { skill: Skill(SkillEnum.Thieving), amount: 500 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Tree-Gnome-Village'),
    name: Name('Tree Gnome Village'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Tree_Gnome_Village',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: 'Gnome',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Attack), amount: 11450 }],
      quest_points: 2,
    },
  },
  {
    id: Id('Tribal-Totem'),
    name: Name('Tribal Totem'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Tribal_Totem',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Thieving), level: 21, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Thieving), amount: 1775 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Troll-Romance'),
    name: Name('Troll Romance'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Troll_Romance',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Troll',
    requirements: { quests: ['Troll Stronghold'], levels: [] },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 8000 },
        { skill: Skill(SkillEnum.Strength), amount: 4000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: Id('Troll-Stronghold'),
    name: Name('Troll Stronghold'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Troll_Stronghold',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short - Medium',
    series: 'Troll',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Agility), level: 15, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: Id('Underground-Pass'),
    name: Name('Underground Pass'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Underground_Pass',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Elf',
    requirements: {
      quests: ['Biohazard'],
      levels: [{ skill: Skill(SkillEnum.Ranged), level: 25, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Agility), amount: 3000 },
        { skill: Skill(SkillEnum.Attack), amount: 3000 },
      ],
      quest_points: 5,
    },
  },
  {
    id: Id('Vampire-Slayer'),
    name: Name('Vampire Slayer'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Vampire_Slayer',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Attack), amount: 4825 }],
      quest_points: 3,
    },
  },
  {
    id: Id('Wanted'),
    name: Name('Wanted!'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Wanted!',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Temple Knight',
    requirements: {
      quests: [
        'Recruitment Drive',
        'Rune Mysteries',
        'The Lost Tribe',
        'Priest in Peril',
      ],
      levels: [
        { skill: Skill(SkillEnum.Quest_points), level: 32, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Slayer), amount: 5000 }],
      quest_points: 1,
    },
  },
  {
    id: Id('Watchtower'),
    name: Name('Watchtower'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Watchtower',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Ogre',
    requirements: {
      quests: [],
      levels: [
        { skill: Skill(SkillEnum.Magic), level: 15, boostable: false },
        { skill: Skill(SkillEnum.Thieving), level: 15, boostable: false },
        { skill: Skill(SkillEnum.Agility), level: 25, boostable: false },
        { skill: Skill(SkillEnum.Herblore), level: 14, boostable: false },
        { skill: Skill(SkillEnum.Mining), level: 40, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Magic), amount: 15250 }],
      quest_points: 4,
    },
  },
  {
    id: Id('Waterfall-Quest'),
    name: Name('Waterfall Quest'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Waterfall_Quest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium (10-20 minutes)',
    series: 'Elf, Gnome',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Attack), amount: 13750 },
        { skill: Skill(SkillEnum.Strength), amount: 13750 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('What-Lies-Below'),
    name: Name('What Lies Below'),
    wiki_url: 'https://oldschool.runescape.wiki/w/What_Lies_Below',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Medium',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Defence), amount: 2000 },
        { skill: Skill(SkillEnum.Runecraft), amount: 8000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: Id('Witchs-House'),
    name: Name("Witch's House"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Witch%27s_House',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Hitpoints), amount: 6325 }],
      quest_points: 4,
    },
  },
  {
    id: Id('Witchs-Potion'),
    name: Name("Witch's Potion"),
    wiki_url: 'https://oldschool.runescape.wiki/w/Witch%27s_Potion',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short (<5 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: Skill(SkillEnum.Magic), amount: 325 }],
      quest_points: 1,
    },
  },
  {
    id: Id('X-Marks-the-Spot'),
    name: Name('X Marks the Spot'),
    wiki_url: 'https://oldschool.runescape.wiki/w/X_Marks_the_Spot',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Great Kourend',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [],
      quest_points: 1,
      other: [
        '200 coins',
        "Antique lamp which provides 300 XP in a skill of the player's choosing.",
        'A beginner clue scroll (only if the player does not have one in their possession; can be claimed later if players had one in their possession already)',
      ],
    },
  },
  {
    id: Id('Zogre-Flesh-Eaters'),
    name: Name('Zogre Flesh Eaters'),
    wiki_url: 'https://oldschool.runescape.wiki/w/Zogre_Flesh_Eaters',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Ogre',
    requirements: {
      quests: ['Big Chompy Bird Hunting', 'Jungle Potion'],
      levels: [
        { skill: Skill(SkillEnum.Smithing), level: 4, boostable: false },
        { skill: Skill(SkillEnum.Herblore), level: 8, boostable: false },
        { skill: Skill(SkillEnum.Ranged), level: 30, boostable: false },
        { skill: Skill(SkillEnum.Fletching), level: 30, boostable: false },
        { skill: Skill(SkillEnum.Strength), level: 10, boostable: false },
        { skill: Skill(SkillEnum.Prayer), level: 43, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: Skill(SkillEnum.Fletching), amount: 2000 },
        { skill: Skill(SkillEnum.Herblore), amount: 2000 },
        { skill: Skill(SkillEnum.Ranged), amount: 2000 },
      ],
      quest_points: 1,
    },
  },
];
export default all_quests;
