export default [
  {
    id: 'A-Souls-Bane',
    name: "A Soul's Bane",
    wiki_url: 'https://oldschool.runescape.wiki/w/A_Soul%27s_Bane',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: 'defence', amount: 500 },
        { skill: 'hitpoints', amount: 500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'A-Tail-of-Two-Cats',
    name: 'A Tail of Two Cats',
    wiki_url: 'https://oldschool.runescape.wiki/w/A_Tail_of_Two_Cats',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Dragonkin',
    requirements: { quests: ["Icthlarin's Little Helper"], levels: [] },
    rewards: { experience: [], quest_points: 2 },
  },
  {
    id: 'A-Taste-of-Hope',
    name: 'A Taste of Hope',
    wiki_url: 'https://oldschool.runescape.wiki/w/A_Taste_of_Hope',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Myreque',
    requirements: {
      quests: ['Darkness of Hallowvale'],
      levels: [
        { skill: 'crafting', level: 48, boostable: false },
        { skill: 'agility', level: 45, boostable: false },
        { skill: 'attack', level: 40, boostable: false },
        { skill: 'herblore', level: 40, boostable: false },
        { skill: 'slayer', level: 38, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: 'Animal-Magnetism',
    name: 'Animal Magnetism',
    wiki_url: 'https://oldschool.runescape.wiki/w/Animal_Magnetism',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: null,
    requirements: {
      quests: ['The Restless Ghost', 'Ernest the Chicken', 'Priest in Peril'],
      levels: [
        { skill: 'slayer', level: 18, boostable: false },
        { skill: 'crafting', level: 19, boostable: false },
        { skill: 'ranged', level: 30, boostable: false },
        { skill: 'woodcutting', level: 35, boostable: false },
        { skill: 'prayer', level: 31, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 1000 },
        { skill: 'fletching', amount: 1000 },
        { skill: 'slayer', amount: 1000 },
        { skill: 'woodcutting', amount: 2500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Another-Slice-of-HAM',
    name: 'Another Slice of H.A.M.',
    wiki_url: 'https://oldschool.runescape.wiki/w/Another_Slice_of_H.A.M.',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Dorgeshuun (#4)',
    requirements: {
      quests: [
        'Death to the Dorgeshuun',
        'The Giant Dwarf',
        'The Dig Site',
        'Druidic Ritual',
      ],
      levels: [
        { skill: 'attack', level: 15, boostable: false },
        { skill: 'prayer', level: 25, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'mining', amount: 3000 },
        { skill: 'prayer', amount: 3000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Between-a-Rock',
    name: 'Between a Rock...',
    wiki_url: 'https://oldschool.runescape.wiki/w/Between_a_Rock...',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium - Long',
    series: 'Rise of the Red Axe',
    requirements: {
      quests: ['Dwarf Cannon', 'Fishing Contest'],
      levels: [
        { skill: 'defence', level: 30, boostable: false },
        { skill: 'mining', level: 40, boostable: true },
        { skill: 'smithing', level: 50, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'defence', amount: 5000 },
        { skill: 'mining', amount: 5000 },
        { skill: 'smithing', amount: 5000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Big-Chompy-Bird-Hunting',
    name: 'Big Chompy Bird Hunting',
    wiki_url: 'https://oldschool.runescape.wiki/w/Big_Chompy_Bird_Hunting',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: 'Ogre',
    requirements: {
      quests: [],
      levels: [
        { skill: 'fletching', level: 5, boostable: false },
        { skill: 'cooking', level: 30, boostable: false },
        { skill: 'ranged', level: 30, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'cooking', amount: 1470 },
        { skill: 'fletching', amount: 262 },
        { skill: 'ranged', amount: 735 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Biohazard',
    name: 'Biohazard',
    wiki_url: 'https://oldschool.runescape.wiki/w/Biohazard',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Elf',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'thieving', amount: 1250 }],
      quest_points: 3,
    },
  },
  {
    id: 'Black-Knights-Fortress',
    name: "Black Knights' Fortress",
    wiki_url: 'https://oldschool.runescape.wiki/w/Black_Knights%27_Fortress',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: 'quest', level: 12, boostable: false }],
    },
    rewards: { experience: [], quest_points: 3 },
  },
  {
    id: 'Bone-Voyage',
    name: 'Bone Voyage',
    wiki_url: 'https://oldschool.runescape.wiki/w/Bone_Voyage',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Medium',
    series: null,
    requirements: { quests: ['The Dig Site'], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: 'Cabin-Fever',
    name: 'Cabin Fever',
    wiki_url: 'https://oldschool.runescape.wiki/w/Cabin_Fever',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Pirate',
    requirements: {
      quests: ["Pirate's Treasure", 'Rum Deal', 'Priest in Peril'],
      levels: [
        { skill: 'agility', level: 42, boostable: false },
        { skill: 'crafting', level: 45, boostable: false },
        { skill: 'smithing', level: 50, boostable: false },
        { skill: 'ranged', level: 40, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 7000 },
        { skill: 'crafting', amount: 7000 },
        { skill: 'smithing', amount: 7000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Client-of-Kourend',
    name: 'Client of Kourend',
    wiki_url: 'https://oldschool.runescape.wiki/w/Client_of_Kourend',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium (15-20 minutes)',
    series: 'Great Kourend',
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: 'Clock-Tower',
    name: 'Clock Tower',
    wiki_url: 'https://oldschool.runescape.wiki/w/Clock_Tower',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: 'Cold-War',
    name: 'Cold War',
    wiki_url: 'https://oldschool.runescape.wiki/w/Cold_War',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: 'Penguin',
    requirements: {
      quests: [],
      levels: [
        { skill: 'hunter', level: 10, boostable: false },
        { skill: 'agility', level: 30, boostable: false },
        { skill: 'crafting', level: 30, boostable: false },
        { skill: 'construction', level: 34, boostable: false },
        { skill: 'thieving', level: 15, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 5000 },
        { skill: 'construction', amount: 1500 },
        { skill: 'crafting', amount: 2000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Contact',
    name: 'Contact!',
    wiki_url: 'https://oldschool.runescape.wiki/w/Contact!',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Medium',
    series: 'Desert',
    requirements: {
      quests: ['Prince Ali Rescue', "Icthlarin's Little Helper"],
      levels: [],
    },
    rewards: {
      experience: [{ skill: 'thieving', amount: 7000 }],
      quest_points: 1,
    },
  },
  {
    id: 'Cooks-Assistant',
    name: "Cook's Assistant",
    wiki_url: 'https://oldschool.runescape.wiki/w/Cook%27s_Assistant',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short (<5 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'cooking', amount: 300 }],
      quest_points: 1,
    },
  },
  {
    id: 'Creature-of-Fenkenstrain',
    name: 'Creature of Fenkenstrain',
    wiki_url: 'https://oldschool.runescape.wiki/w/Creature_of_Fenkenstrain',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: null,
    requirements: {
      quests: ['Priest in Peril', 'The Restless Ghost'],
      levels: [
        { skill: 'crafting', level: 20, boostable: false },
        { skill: 'thieving', level: 25, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: 'thieving', amount: 1000 }],
      quest_points: 2,
    },
  },
  {
    id: 'Darkness-of-Hallowvale',
    name: 'Darkness of Hallowvale',
    wiki_url: 'https://oldschool.runescape.wiki/w/Darkness_of_Hallowvale',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Very long',
    series: 'Myreque',
    requirements: {
      quests: ['In Aid of the Myreque'],
      levels: [
        { skill: 'construction', level: 5, boostable: false },
        { skill: 'mining', level: 20, boostable: true },
        { skill: 'thieving', level: 22, boostable: false },
        { skill: 'agility', level: 26, boostable: false },
        { skill: 'crafting', level: 32, boostable: false },
        { skill: 'magic', level: 33, boostable: false },
        { skill: 'strength', level: 40, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 7000 },
        { skill: 'construction', amount: 2000 },
        { skill: 'thieving', amount: 6000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Death-Plateau',
    name: 'Death Plateau',
    wiki_url: 'https://oldschool.runescape.wiki/w/Death_Plateau',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Troll',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'attack', amount: 3000 }],
      quest_points: 1,
    },
  },
  {
    id: 'Death-to-the-Dorgeshuun',
    name: 'Death to the Dorgeshuun',
    wiki_url: 'https://oldschool.runescape.wiki/w/Death_to_the_Dorgeshuun',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Dorgeshuun',
    requirements: {
      quests: ['The Lost Tribe'],
      levels: [
        { skill: 'agility', level: 23, boostable: false },
        { skill: 'thieving', level: 23, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'ranged', amount: 2000 },
        { skill: 'thieving', amount: 2000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Demon-Slayer',
    name: 'Demon Slayer',
    wiki_url: 'https://oldschool.runescape.wiki/w/Demon_Slayer',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 3 },
  },
  {
    id: 'Desert-Treasure',
    name: 'Desert Treasure',
    wiki_url: 'https://oldschool.runescape.wiki/w/Desert_Treasure',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Very long',
    series: 'The Return of Zaros and Mahjarrat',
    requirements: {
      quests: [
        'The Dig Site',
        'Temple of Ikov',
        'The Tourist Trap',
        'Troll Stronghold',
        'Priest in Peril',
        'Waterfall Quest',
      ],
      levels: [
        { skill: 'thieving', level: 53, boostable: true },
        { skill: 'firemaking', level: 50, boostable: false },
        { skill: 'slayer', level: 10, boostable: false },
        { skill: 'magic', level: 50, boostable: true },
      ],
    },
    rewards: {
      experience: [{ skill: 'magic', amount: 20000 }],
      quest_points: 3,
    },
  },
  {
    id: 'Devious-Minds',
    name: 'Devious Minds',
    wiki_url: 'https://oldschool.runescape.wiki/w/Devious_Minds',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short',
    series: 'The Return of Zaros',
    requirements: {
      quests: [
        'Wanted!',
        'Troll Stronghold',
        "Doric's Quest",
        'Enter the Abyss',
      ],
      levels: [
        { skill: 'smithing', level: 65, boostable: true },
        { skill: 'runecrafting', level: 50, boostable: false },
        { skill: 'fletching', level: 50, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'fletching', amount: 5000 },
        { skill: 'runecrafting', amount: 5000 },
        { skill: 'smithing', amount: 6500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Dorics-Quest',
    name: "Doric's Quest",
    wiki_url: 'https://oldschool.runescape.wiki/w/Doric%27s_Quest',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: 'mining', level: 15, boostable: false }],
    },
    rewards: {
      experience: [{ skill: 'mining', amount: 1300 }],
      quest_points: 1,
    },
  },
  {
    id: 'Dragon-Slayer',
    name: 'Dragon Slayer',
    wiki_url: 'https://oldschool.runescape.wiki/w/Dragon_Slayer',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Guild',
    requirements: {
      quests: [],
      levels: [
        { skill: 'quest', level: 32, boostable: false },
        { skill: 'crafting', level: 8, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'defence', amount: 18650 },
        { skill: 'strength', amount: 18650 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Dragon-Slayer-II',
    name: 'Dragon Slayer II',
    wiki_url: 'https://oldschool.runescape.wiki/w/Dragon_Slayer_II',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Grandmaster',
    length: 'Very long',
    series: 'Dragonkin',
    requirements: {
      quests: [
        "Legends' Quest",
        'Dream Mentor',
        'A Tail of Two Cats',
        'Animal Magnetism',
        'Ghosts Ahoy',
        'Bone Voyage',
        'Client of Kourend',
      ],
      levels: [{ skill: 'quest', level: 200, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 15000 },
        { skill: 'mining', amount: 18000 },
        { skill: 'smithing', amount: 25000 },
        { skill: 'thieving', amount: 15000 },
      ],
      quest_points: 5,
    },
  },
  {
    id: 'Dream-Mentor',
    name: 'Dream Mentor',
    wiki_url: 'https://oldschool.runescape.wiki/w/Dream_Mentor',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Short - Medium',
    series: 'Fremennik',
    requirements: {
      quests: ['Lunar Diplomacy', "Eadgar's Ruse"],
      levels: [{ skill: 'combat', level: 85, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'hitpoints', amount: 15000 },
        { skill: 'magic', amount: 10000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Druidic-Ritual',
    name: 'Druidic Ritual',
    wiki_url: 'https://oldschool.runescape.wiki/w/Druidic_Ritual',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'herblore', amount: 250 }],
      quest_points: 4,
    },
  },
  {
    id: 'Dwarf-Cannon',
    name: 'Dwarf Cannon',
    wiki_url: 'https://oldschool.runescape.wiki/w/Dwarf_Cannon',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'crafting', amount: 750 }],
      quest_points: 1,
    },
  },
  {
    id: 'Eadgars-Ruse',
    name: "Eadgar's Ruse",
    wiki_url: 'https://oldschool.runescape.wiki/w/Eadgar%27s_Ruse',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium - Long',
    series: 'Troll',
    requirements: {
      quests: ['Druidic Ritual', 'Troll Stronghold'],
      levels: [
        { skill: 'herblore', level: 31, boostable: true },
        { skill: 'agility', level: 44, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: 'herblore', amount: 11000 }],
      quest_points: 1,
    },
  },
  {
    id: 'Eagles-Peak',
    name: "Eagles' Peak",
    wiki_url: 'https://oldschool.runescape.wiki/w/Eagles%27_Peak',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: 'hunter', level: 27, boostable: true }],
    },
    rewards: {
      experience: [{ skill: 'hunter', amount: 2500 }],
      quest_points: 2,
    },
  },
  {
    id: 'Elemental-Workshop-I',
    name: 'Elemental Workshop I',
    wiki_url: 'https://oldschool.runescape.wiki/w/Elemental_Workshop_I',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Elemental Workshop',
    requirements: {
      quests: [],
      levels: [
        { skill: 'mining', level: 20, boostable: false },
        { skill: 'smithing', level: 20, boostable: false },
        { skill: 'crafting', level: 20, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 5000 },
        { skill: 'smithing', amount: 5000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Elemental-Workshop-II',
    name: 'Elemental Workshop II',
    wiki_url: 'https://oldschool.runescape.wiki/w/Elemental_Workshop_II',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Elemental Workshop (#2)',
    requirements: {
      quests: [],
      levels: [
        { skill: 'magic', level: 20, boostable: false },
        { skill: 'smithing', level: 30, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 7500 },
        { skill: 'smithing', amount: 7500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Enakhras-Lament',
    name: "Enakhra's Lament",
    wiki_url: 'https://oldschool.runescape.wiki/w/Enakhra%27s_Lament',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Mahjarrat',
    requirements: {
      quests: [],
      levels: [
        { skill: 'crafting', level: 50, boostable: false },
        { skill: 'firemaking', level: 45, boostable: false },
        { skill: 'prayer', level: 43, boostable: false },
        { skill: 'magic', level: 39, boostable: false },
        { skill: 'mining', level: 45, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 7000 },
        { skill: 'firemaking', amount: 7000 },
        { skill: 'magic', amount: 7000 },
        { skill: 'mining', amount: 7000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Enlightened-Journey',
    name: 'Enlightened Journey',
    wiki_url: 'https://oldschool.runescape.wiki/w/Enlightened_Journey',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Long',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: 'quest', level: 20, boostable: false },
        { skill: 'firemaking', level: 20, boostable: false },
        { skill: 'farming', level: 30, boostable: true },
        { skill: 'crafting', level: 36, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 2000 },
        { skill: 'farming', amount: 3000 },
        { skill: 'firemaking', amount: 4000 },
        { skill: 'woodcutting', amount: 1500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Enter-the-Abyss',
    name: 'Enter the Abyss',
    wiki_url: 'https://oldschool.runescape.wiki/w/Enter_the_Abyss',
    is_members_only: true,
    is_miniquest: true,
    difficulty: 'Novice',
    length: 'Short â€“ Long',
    series: null,
    requirements: { quests: ['Rune Mysteries'], levels: [] },
    rewards: { experience: [], quest_points: 0 },
  },
  {
    id: 'Ernest-the-Chicken',
    name: 'Ernest the Chicken',
    wiki_url: 'https://oldschool.runescape.wiki/w/Ernest_the_Chicken',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 4 },
  },
  {
    id: 'Fairytale-I---Growing-Pains',
    name: 'Fairytale I - Growing Pains',
    wiki_url: 'https://oldschool.runescape.wiki/w/Fairytale_I_-_Growing_Pains',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Fairy Tale (#2)',
    requirements: { quests: ['Lost City', 'Nature Spirit'], levels: [] },
    rewards: {
      experience: [
        { skill: 'attack', amount: 2000 },
        { skill: 'farming', amount: 3500 },
        { skill: 'magic', amount: 1000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Fairytale-II---Cure-a-Queen',
    name: 'Fairytale II - Cure a Queen',
    wiki_url: 'https://oldschool.runescape.wiki/w/Fairytale_II_-_Cure_a_Queen',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short - Medium',
    series: 'Fairy Tale (#2)',
    requirements: {
      quests: ['Fairytale I - Growing Pains'],
      levels: [
        { skill: 'thieving', level: 40, boostable: true },
        { skill: 'farming', level: 49, boostable: true },
        { skill: 'herblore', level: 57, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'herblore', amount: 3500 },
        { skill: 'thieving', amount: 2500 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Family-Crest',
    name: 'Family Crest',
    wiki_url: 'https://oldschool.runescape.wiki/w/Family_Crest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: 'mining', level: 40, boostable: true },
        { skill: 'smithing', level: 40, boostable: true },
        { skill: 'magic', level: 59, boostable: true },
        { skill: 'crafting', level: 40, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: 'Fight-Arena',
    name: 'Fight Arena',
    wiki_url: 'https://oldschool.runescape.wiki/w/Fight_Arena',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short',
    series: 'Mahjarrat',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: 'attack', amount: 12175 },
        { skill: 'thieving', amount: 2175 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Fishing-Contest',
    name: 'Fishing Contest',
    wiki_url: 'https://oldschool.runescape.wiki/w/Fishing_Contest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Dwarf',
    requirements: {
      quests: [],
      levels: [{ skill: 'fishing', level: 10, boostable: false }],
    },
    rewards: {
      experience: [{ skill: 'fishing', amount: 2437 }],
      quest_points: 1,
    },
  },
  {
    id: 'Forgettable-Tale',
    name: 'Forgettable Tale...',
    wiki_url: 'https://oldschool.runescape.wiki/w/Forgettable_Tale...',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Rise of the Red Axe',
    requirements: {
      quests: ['The Giant Dwarf', 'Fishing Contest'],
      levels: [
        { skill: 'cooking', level: 22, boostable: false },
        { skill: 'farming', level: 17, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'cooking', amount: 5000 },
        { skill: 'farming', amount: 5000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Garden-of-Tranquillity',
    name: 'Garden of Tranquillity',
    wiki_url: 'https://oldschool.runescape.wiki/w/Garden_of_Tranquillity',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Very long',
    series: null,
    requirements: {
      quests: ['Creature of Fenkenstrain'],
      levels: [{ skill: 'farming', level: 25, boostable: false }],
    },
    rewards: {
      experience: [{ skill: 'farming', amount: 5000 }],
      quest_points: 2,
    },
  },
  {
    id: 'Gertrudes-Cat',
    name: "Gertrude's Cat",
    wiki_url: 'https://oldschool.runescape.wiki/w/Gertrude%27s_Cat',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'cooking', amount: 1525 }],
      quest_points: 1,
    },
  },
  {
    id: 'Ghosts-Ahoy',
    name: 'Ghosts Ahoy',
    wiki_url: 'https://oldschool.runescape.wiki/w/Ghosts_Ahoy',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'prayer', amount: 2400 }],
      quest_points: 2,
    },
  },
  {
    id: 'Goblin-Diplomacy',
    name: 'Goblin Diplomacy',
    wiki_url: 'https://oldschool.runescape.wiki/w/Goblin_Diplomacy',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'crafting', amount: 200 }],
      quest_points: 5,
    },
  },
  {
    id: 'Grim-Tales',
    name: 'Grim Tales',
    wiki_url: 'https://oldschool.runescape.wiki/w/Grim_Tales',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: 'farming', level: 45, boostable: true },
        { skill: 'herblore', level: 52, boostable: true },
        { skill: 'thieving', level: 58, boostable: true },
        { skill: 'agility', level: 59, boostable: true },
        { skill: 'woodcutting', level: 71, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 6000 },
        { skill: 'farming', amount: 4000 },
        { skill: 'herblore', amount: 5000 },
        { skill: 'hitpoints', amount: 5000 },
        { skill: 'thieving', amount: 6000 },
        { skill: 'woodcutting', amount: 14000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Haunted-Mine',
    name: 'Haunted Mine',
    wiki_url: 'https://oldschool.runescape.wiki/w/Haunted_Mine',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium - Long',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: 'agility', level: 15, boostable: false },
        { skill: 'crafting', level: 35, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: 'strength', amount: 22000 }],
      quest_points: 2,
    },
  },
  {
    id: 'Hazeel-Cult',
    name: 'Hazeel Cult',
    wiki_url: 'https://oldschool.runescape.wiki/w/Hazeel_Cult',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Mahjarrat',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'thieving', amount: 1500 }],
      quest_points: 1,
    },
  },
  {
    id: 'Heroes-Quest',
    name: "Heroes' Quest",
    wiki_url: 'https://oldschool.runescape.wiki/w/Heroes%27_Quest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium - Long',
    series: 'Guild',
    requirements: {
      quests: [
        'Shield of Arrav',
        'Lost City',
        "Merlin's Crystal",
        'Dragon Slayer',
        'Druidic Ritual',
      ],
      levels: [{ skill: 'quest', level: 55, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'attack', amount: 3075 },
        { skill: 'cooking', amount: 2825 },
        { skill: 'defence', amount: 3075 },
        { skill: 'firemaking', amount: 1575 },
        { skill: 'fishing', amount: 2725 },
        { skill: 'herblore', amount: 1325 },
        { skill: 'hitpoints', amount: 3075 },
        { skill: 'mining', amount: 2575 },
        { skill: 'ranged', amount: 2075 },
        { skill: 'smithing', amount: 2257 },
        { skill: 'strength', amount: 3075 },
        { skill: 'woodcutting', amount: 1575 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Holy-Grail',
    name: 'Holy Grail',
    wiki_url: 'https://oldschool.runescape.wiki/w/Holy_Grail',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Camelot (#2)',
    requirements: {
      quests: [],
      levels: [{ skill: 'attack', level: 20, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'defence', amount: 15300 },
        { skill: 'prayer', amount: 11000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Horror-from-the-Deep',
    name: 'Horror from the Deep',
    wiki_url: 'https://oldschool.runescape.wiki/w/Horror_from_the_Deep',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [{ skill: 'agility', level: 35, boostable: true }],
    },
    rewards: {
      experience: [
        { skill: 'magic', amount: 4662 },
        { skill: 'ranged', amount: 4662.5 },
        { skill: 'strength', amount: 4662.5 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Icthlarins-Little-Helper',
    name: "Icthlarin's Little Helper",
    wiki_url: 'https://oldschool.runescape.wiki/w/Icthlarin%27s_Little_Helper',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: 'Desert',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: 'agility', amount: 4000 },
        { skill: 'thieving', amount: 4500 },
        { skill: 'woodcutting', amount: 4000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Imp-Catcher',
    name: 'Imp Catcher',
    wiki_url: 'https://oldschool.runescape.wiki/w/Imp_Catcher',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short (<5-15 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [{ skill: 'magic', amount: 875 }], quest_points: 1 },
  },
  {
    id: 'In-Aid-of-the-Myreque',
    name: 'In Aid of the Myreque',
    wiki_url: 'https://oldschool.runescape.wiki/w/In_Aid_of_the_Myreque',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Myreque',
    requirements: {
      quests: ['In Search of the Myreque'],
      levels: [
        { skill: 'crafting', level: 25, boostable: false },
        { skill: 'mining', level: 15, boostable: false },
        { skill: 'magic', level: 7, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'attack', amount: 2000 },
        { skill: 'crafting', amount: 2000 },
        { skill: 'defence', amount: 2000 },
        { skill: 'strength', amount: 2000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'In-Search-of-the-Myreque',
    name: 'In Search of the Myreque',
    wiki_url: 'https://oldschool.runescape.wiki/w/In_Search_of_the_Myreque',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: 'Myreque',
    requirements: {
      quests: ['Nature Spirit'],
      levels: [{ skill: 'agility', level: 25, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'attack', amount: 600 },
        { skill: 'crafting', amount: 600 },
        { skill: 'defence', amount: 600 },
        { skill: 'hitpoints', amount: 600 },
        { skill: 'strength', amount: 600 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Jungle-Potion',
    name: 'Jungle Potion',
    wiki_url: 'https://oldschool.runescape.wiki/w/Jungle_Potion',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short - Medium',
    series: 'Karamja',
    requirements: {
      quests: [],
      levels: [{ skill: 'herblore', level: 3, boostable: false }],
    },
    rewards: {
      experience: [{ skill: 'herblore', amount: 775 }],
      quest_points: 1,
    },
  },
  {
    id: 'Kings-Ransom',
    name: "King's Ransom",
    wiki_url: 'https://oldschool.runescape.wiki/w/King%27s_Ransom',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Camelot (#3)',
    requirements: {
      quests: [
        "Black Knights' Fortress",
        'Holy Grail',
        'Murder Mystery',
        'One Small Favour',
      ],
      levels: [
        { skill: 'magic', level: 45, boostable: false },
        { skill: 'defence', level: 65, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'defence', amount: 33000 },
        { skill: 'magic', amount: 5000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Legends-Quest',
    name: "Legends' Quest",
    wiki_url: 'https://oldschool.runescape.wiki/w/Legends%27_Quest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Very long',
    series: 'Karamja, Guild',
    requirements: {
      quests: [
        'Family Crest',
        "Heroes' Quest",
        'Shilo Village',
        'Underground Pass',
        'Waterfall Quest',
      ],
      levels: [
        { skill: 'quest', level: 107, boostable: false },
        { skill: 'agility', level: 50, boostable: true },
        { skill: 'crafting', level: 50, boostable: false },
        { skill: 'herblore', level: 45, boostable: true },
        { skill: 'magic', level: 56, boostable: false },
        { skill: 'mining', level: 52, boostable: true },
        { skill: 'prayer', level: 42, boostable: true },
        { skill: 'smithing', level: 50, boostable: true },
        { skill: 'strength', level: 50, boostable: true },
        { skill: 'thieving', level: 50, boostable: false },
        { skill: 'woodcutting', level: 50, boostable: true },
      ],
    },
    rewards: { experience: [], quest_points: 4 },
  },
  {
    id: 'Lost-City',
    name: 'Lost City',
    wiki_url: 'https://oldschool.runescape.wiki/w/Lost_City',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short',
    series: 'Fairy Tale',
    requirements: {
      quests: [],
      levels: [
        { skill: 'crafting', level: 31, boostable: false },
        { skill: 'woodcutting', level: 36, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 3 },
  },
  {
    id: 'Lunar-Diplomacy',
    name: 'Lunar Diplomacy',
    wiki_url: 'https://oldschool.runescape.wiki/w/Lunar_Diplomacy',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Fremennik',
    requirements: {
      quests: [
        'The Fremennik Trials',
        'Lost City',
        'Rune Mysteries',
        'Shilo Village',
      ],
      levels: [
        { skill: 'crafting', level: 61, boostable: false },
        { skill: 'defence', level: 40, boostable: false },
        { skill: 'firemaking', level: 49, boostable: false },
        { skill: 'magic', level: 65, boostable: false },
        { skill: 'mining', level: 60, boostable: false },
        { skill: 'woodcutting', level: 55, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'magic', amount: 5000 },
        { skill: 'runecrafting', amount: 5000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Making-Friends-with-My-Arm',
    name: 'Making Friends with My Arm',
    wiki_url: 'https://oldschool.runescape.wiki/w/Making_Friends_with_My_Arm',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Medium',
    series: 'Troll',
    requirements: {
      quests: [
        "My Arm's Big Adventure",
        'Swan Song',
        'Cold War',
        'Romeo & Juliet',
      ],
      levels: [
        { skill: 'firemaking', level: 66, boostable: false },
        { skill: 'mining', level: 72, boostable: false },
        { skill: 'construction', level: 35, boostable: false },
        { skill: 'agility', level: 68, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 10000 },
        { skill: 'construction', amount: 2000 },
        { skill: 'firemaking', amount: 5000 },
        { skill: 'mining', amount: 10000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Making-History',
    name: 'Making History',
    wiki_url: 'https://oldschool.runescape.wiki/w/Making_History',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Long',
    series: 'Enchanted Key',
    requirements: {
      quests: ['Priest in Peril', 'The Restless Ghost'],
      levels: [],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 1000 },
        { skill: 'prayer', amount: 1000 },
      ],
      quest_points: 3,
    },
  },
  {
    id: 'Merlins-Crystal',
    name: "Merlin's Crystal",
    wiki_url: 'https://oldschool.runescape.wiki/w/Merlin%27s_Crystal',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium-Long (Under 10 minutes with teleports)',
    series: 'Camelot',
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 6 },
  },
  {
    id: 'Misthalin-Mystery',
    name: 'Misthalin Mystery',
    wiki_url: 'https://oldschool.runescape.wiki/w/Misthalin_Mystery',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'crafting', amount: 600 }],
      quest_points: 1,
    },
  },
  {
    id: 'Monks-Friend',
    name: "Monk's Friend",
    wiki_url: 'https://oldschool.runescape.wiki/w/Monk%27s_Friend',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Very Short (5 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'woodcutting', amount: 2000 }],
      quest_points: 1,
    },
  },
  {
    id: 'Monkey-Madness-I',
    name: 'Monkey Madness I',
    wiki_url: 'https://oldschool.runescape.wiki/w/Monkey_Madness_I',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Long',
    series: 'Gnome, Monkey',
    requirements: {
      quests: ['The Grand Tree', 'Tree Gnome Village'],
      levels: [{ skill: 'prayer', level: 43, boostable: false }],
    },
    rewards: { experience: [], quest_points: 3 },
  },
  {
    id: 'Monkey-Madness-II',
    name: 'Monkey Madness II',
    wiki_url: 'https://oldschool.runescape.wiki/w/Monkey_Madness_II',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Grandmaster',
    length: 'Very long',
    series: 'Gnome, Monkey',
    requirements: {
      quests: [
        'Enlightened Journey',
        'The Eyes of Glouphrie',
        'Recipe for Disaster',
        'Troll Stronghold',
        'Watchtower',
      ],
      levels: [
        { skill: 'slayer', level: 69, boostable: false },
        { skill: 'crafting', level: 70, boostable: false },
        { skill: 'hunter', level: 60, boostable: false },
        { skill: 'agility', level: 55, boostable: false },
        { skill: 'thieving', level: 55, boostable: false },
        { skill: 'firemaking', level: 60, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 20000 },
        { skill: 'hunter', amount: 15000 },
        { skill: 'slayer', amount: 25000 },
        { skill: 'thieving', amount: 15000 },
      ],
      quest_points: 4,
    },
  },
  {
    id: 'Mountain-Daughter',
    name: 'Mountain Daughter',
    wiki_url: 'https://oldschool.runescape.wiki/w/Mountain_Daughter',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [{ skill: 'agility', level: 20, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'attack', amount: 1000 },
        { skill: 'prayer', amount: 2000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Mournings-End-Part-I',
    name: "Mourning's End Part I",
    wiki_url: 'https://oldschool.runescape.wiki/w/Mourning%27s_Ends_Part_I',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Short',
    series: 'Elf',
    requirements: {
      quests: ['Roving Elves', 'Big Chompy Bird Hunting', 'Sheep Herder'],
      levels: [
        { skill: 'ranged', level: 60, boostable: true },
        { skill: 'thieving', level: 50, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'hitpoints', amount: 25000 },
        { skill: 'thieving', amount: 25000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Mournings-End-Part-II',
    name: "Mourning's End Part II",
    wiki_url: 'https://oldschool.runescape.wiki/w/Mourning%27s_Ends_Part_II',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Short',
    series: 'Elf',
    requirements: {
      quests: [],
      levels: [
        { skill: 'prayer', level: 43, boostable: false },
        { skill: 'agility', level: 60, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: 'agility', amount: 20000 }],
      quest_points: 1,
    },
  },
  {
    id: 'Murder-Mystery',
    name: 'Murder Mystery',
    wiki_url: 'https://oldschool.runescape.wiki/w/Murder_Mystery',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Camelot',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'crafting', amount: 1406 }],
      quest_points: 3,
    },
  },
  {
    id: 'My-Arms-Big-Adventure',
    name: "My Arm's Big Adventure",
    wiki_url: 'https://oldschool.runescape.wiki/w/My_Arm%27s_Big_Adventure',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Troll',
    requirements: {
      quests: ["Eadgar's Ruse", 'The Feud', 'Jungle Potion'],
      levels: [
        { skill: 'woodcutting', level: 10, boostable: false },
        { skill: 'farming', level: 29, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'farming', amount: 5000 },
        { skill: 'herblore', amount: 10000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Nature-Spirit',
    name: 'Nature Spirit',
    wiki_url: 'https://oldschool.runescape.wiki/w/Nature_Spirit',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Myreque',
    requirements: {
      quests: ['Priest in Peril', 'The Restless Ghost'],
      levels: [{ skill: 'crafting', level: 18, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 3000 },
        { skill: 'defence', amount: 2000 },
        { skill: 'hitpoints', amount: 2000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Observatory-Quest',
    name: 'Observatory Quest',
    wiki_url: 'https://oldschool.runescape.wiki/w/Observatory_Quest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short - Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: 'crafting', level: 10, boostable: false }],
    },
    rewards: {
      experience: [{ skill: 'crafting', amount: 2250 }],
      quest_points: 2,
    },
  },
  {
    id: 'Olafs-Quest',
    name: "Olaf's Quest",
    wiki_url: 'https://oldschool.runescape.wiki/w/Olaf%27s_Quest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Long',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [
        { skill: 'firemaking', level: 40, boostable: false },
        { skill: 'woodcutting', level: 50, boostable: true },
      ],
    },
    rewards: {
      experience: [{ skill: 'defence', amount: 12000 }],
      quest_points: 1,
    },
  },
  {
    id: 'One-Small-Favour',
    name: 'One Small Favour',
    wiki_url: 'https://oldschool.runescape.wiki/w/One_Small_Favour',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Very long',
    series: 'Karamja',
    requirements: {
      quests: ['Rune Mysteries', 'Shilo Village'],
      levels: [
        { skill: 'agility', level: 36, boostable: true },
        { skill: 'crafting', level: 25, boostable: false },
        { skill: 'herblore', level: 18, boostable: false },
        { skill: 'smithing', level: 30, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 2 },
  },
  {
    id: 'Pirates-Treasure',
    name: "Pirate's Treasure",
    wiki_url: 'https://oldschool.runescape.wiki/w/Pirate%27s_Treasure',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Pirate',
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 2 },
  },
  {
    id: 'Plague-City',
    name: 'Plague City',
    wiki_url: 'https://oldschool.runescape.wiki/w/Plague_City',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Elf',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'mining', amount: 2425 }],
      quest_points: 1,
    },
  },
  {
    id: 'Priest-in-Peril',
    name: 'Priest in Peril',
    wiki_url: 'https://oldschool.runescape.wiki/w/Priest_in_Peril',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Myreque',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'prayer', amount: 1406 }],
      quest_points: 1,
    },
  },
  {
    id: 'Prince-Ali-Rescue',
    name: 'Prince Ali Rescue',
    wiki_url: 'https://oldschool.runescape.wiki/w/Prince_Ali_Rescue',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 3 },
  },
  {
    id: 'Rag-and-Bone-Man',
    name: 'Rag and Bone Man',
    wiki_url: 'https://oldschool.runescape.wiki/w/Rag_and_Bone_Man',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: 'cooking', amount: 500 },
        { skill: 'prayer', amount: 500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Rag-and-Bone-Man-II',
    name: 'Rag and Bone Man II',
    wiki_url: 'https://oldschool.runescape.wiki/w/Rag_and_Bone_Man_II',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: 'slayer', level: 40, boostable: false },
        { skill: 'defence', level: 20, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: 'prayer', amount: 5000 }],
      quest_points: 1,
    },
  },
  {
    id: 'Ratcatchers',
    name: 'Ratcatchers',
    wiki_url: 'https://oldschool.runescape.wiki/w/Ratcatchers',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long - Very long',
    series: null,
    requirements: { quests: ["Icthlarin's Little Helper"], levels: [] },
    rewards: {
      experience: [{ skill: 'thieving', amount: 4500 }],
      quest_points: 2,
    },
  },
  {
    id: 'Recipe-for-Disaster',
    name: 'Recipe for Disaster',
    wiki_url: 'https://oldschool.runescape.wiki/w/Recipe_for_Disaster',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Special',
    length: 'Very long',
    series: null,
    requirements: {
      quests: [
        "Cook's Assistant",
        'Fishing Contest',
        'Goblin Diplomacy',
        'Big Chompy Bird Hunting',
        'Murder Mystery',
        'Nature Spirit',
        "Witch's House",
        "Gertrude's Cat",
        'Shadow of the Storm',
        "Started Legends' Quest",
        'Monkey Madness I',
        'Desert Treasure',
        'Horror from the Deep',
      ],
      levels: [
        { skill: 'quest', level: 175, boostable: false },
        { skill: 'cooking', level: 70, boostable: true },
        { skill: 'agility', level: 48, boostable: false },
        { skill: 'mining', level: 50, boostable: true },
        { skill: 'fishing', level: 53, boostable: true },
        { skill: 'thieving', level: 53, boostable: false },
        { skill: 'herblore', level: 25, boostable: true },
        { skill: 'magic', level: 59, boostable: true },
        { skill: 'smithing', level: 40, boostable: false },
        { skill: 'firemaking', level: 50, boostable: false },
        { skill: 'ranged', level: 40, boostable: false },
        { skill: 'crafting', level: 40, boostable: false },
        { skill: 'fletching', level: 10, boostable: false },
        { skill: 'slayer', level: 10, boostable: false },
        { skill: 'woodcutting', level: 36, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 10 },
  },
  {
    id: 'Recruitment-Drive',
    name: 'Recruitment Drive',
    wiki_url: 'https://oldschool.runescape.wiki/w/Recruitment_Drive',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Temple Knight',
    requirements: {
      quests: [],
      levels: [{ skill: 'quest', level: 12, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 1000 },
        { skill: 'herblore', amount: 1000 },
        { skill: 'prayer', amount: 1000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Regicide',
    name: 'Regicide',
    wiki_url: 'https://oldschool.runescape.wiki/w/Regicide',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Long',
    series: 'Elf',
    requirements: {
      quests: ['Underground Pass'],
      levels: [
        { skill: 'agility', level: 56, boostable: true },
        { skill: 'crafting', level: 10, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: 'agility', amount: 13750 }],
      quest_points: 3,
    },
  },
  {
    id: 'Romeo--Juliet',
    name: 'Romeo & Juliet',
    wiki_url: 'https://oldschool.runescape.wiki/w/Romeo_%26_Juliet',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 5 },
  },
  {
    id: 'Roving-Elves',
    name: 'Roving Elves',
    wiki_url: 'https://oldschool.runescape.wiki/w/Roving_Elves',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Short - Medium',
    series: 'Elf, Gnome',
    requirements: { quests: ['Regicide', 'Waterfall Quest'], levels: [] },
    rewards: {
      experience: [{ skill: 'strength', amount: 10000 }],
      quest_points: 1,
    },
  },
  {
    id: 'Royal-Trouble',
    name: 'Royal Trouble',
    wiki_url: 'https://oldschool.runescape.wiki/w/Royal_Trouble',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [
        { skill: 'agility', level: 40, boostable: true },
        { skill: 'slayer', level: 40, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 5000 },
        { skill: 'hitpoints', amount: 5000 },
        { skill: 'slayer', amount: 5000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Rum-Deal',
    name: 'Rum Deal',
    wiki_url: 'https://oldschool.runescape.wiki/w/Rum_Deal',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Pirate',
    requirements: {
      quests: ['Zogre Flesh Eaters', 'Priest in Peril'],
      levels: [
        { skill: 'crafting', level: 42, boostable: false },
        { skill: 'fishing', level: 50, boostable: true },
        { skill: 'farming', level: 40, boostable: true },
        { skill: 'prayer', level: 47, boostable: true },
        { skill: 'slayer', level: 42, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'farming', amount: 7000 },
        { skill: 'fishing', amount: 7000 },
        { skill: 'prayer', amount: 7000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Rune-Mysteries',
    name: 'Rune Mysteries',
    wiki_url: 'https://oldschool.runescape.wiki/w/Rune_Mysteries',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short (<5 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: 'Scorpion-Catcher',
    name: 'Scorpion Catcher',
    wiki_url: 'https://oldschool.runescape.wiki/w/Scorpion_Catcher',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: 'prayer', level: 31, boostable: false }],
    },
    rewards: {
      experience: [{ skill: 'strength', amount: 6625 }],
      quest_points: 1,
    },
  },
  {
    id: 'Sea-Slug',
    name: 'Sea Slug',
    wiki_url: 'https://oldschool.runescape.wiki/w/Sea_Slug',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: 'Sea Slug',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'fishing', amount: 7175 }],
      quest_points: 1,
    },
  },
  {
    id: 'Shades-of-Mortton',
    name: "Shades of Mort'ton",
    wiki_url: 'https://oldschool.runescape.wiki/w/Shades_of_Mort%27ton',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: "Mort'ton",
    requirements: {
      quests: [],
      levels: [
        { skill: 'crafting', level: 20, boostable: false },
        { skill: 'herblore', level: 15, boostable: false },
        { skill: 'firemaking', level: 5, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 2000 },
        { skill: 'herblore', amount: 2000 },
      ],
      quest_points: 3,
    },
  },
  {
    id: 'Shadow-of-the-Storm',
    name: 'Shadow of the Storm',
    wiki_url: 'https://oldschool.runescape.wiki/w/Shadow_of_the_Storm',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: null,
    requirements: { quests: ['The Golem', 'Demon Slayer'], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: 'Sheep-Herder',
    name: 'Sheep Herder',
    wiki_url: 'https://oldschool.runescape.wiki/w/Sheep_Herder',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short/Medium',
    series: 'Plague/Elf',
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 4 },
  },
  {
    id: 'Sheep-Shearer',
    name: 'Sheep Shearer',
    wiki_url: 'https://oldschool.runescape.wiki/w/Sheep_Shearer',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'crafting', amount: 150 }],
      quest_points: 1,
    },
  },
  {
    id: 'Shield-of-Arrav',
    name: 'Shield of Arrav',
    wiki_url: 'https://oldschool.runescape.wiki/w/Shield_of_Arrav',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Mahjarrat',
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: 'Shilo-Village',
    name: 'Shilo Village',
    wiki_url: 'https://oldschool.runescape.wiki/w/Shilo_Village',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium - Long',
    series: 'Karamja',
    requirements: {
      quests: [],
      levels: [
        { skill: 'crafting', level: 20, boostable: false },
        { skill: 'agility', level: 32, boostable: true },
        { skill: 'smithing', level: 4, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: 'crafting', amount: 3875 }],
      quest_points: 2,
    },
  },
  {
    id: 'Song-of-the-Elves',
    name: 'Song of the Elves',
    wiki_url: 'https://oldschool.runescape.wiki/w/Song_of_the_Elves',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Grandmaster',
    length: 'Very long',
    series: 'Elf',
    requirements: {
      quests: ["Mourning's End Part II", 'Making History'],
      levels: [
        { skill: 'agility', level: 70, boostable: false },
        { skill: 'construction', level: 70, boostable: false },
        { skill: 'farming', level: 70, boostable: false },
        { skill: 'herblore', level: 70, boostable: false },
        { skill: 'hunter', level: 70, boostable: false },
        { skill: 'mining', level: 70, boostable: false },
        { skill: 'smithing', level: 70, boostable: false },
        { skill: 'woodcutting', level: 70, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 20000 },
        { skill: 'construction', amount: 20000 },
        { skill: 'farming', amount: 20000 },
        { skill: 'herblore', amount: 20000 },
        { skill: 'hunter', amount: 20000 },
        { skill: 'mining', amount: 20000 },
        { skill: 'smithing', amount: 20000 },
        { skill: 'woodcutting', amount: 20000 },
      ],
      quest_points: 4,
    },
  },
  {
    id: 'Spirits-of-the-Elid',
    name: 'Spirits of the Elid',
    wiki_url: 'https://oldschool.runescape.wiki/w/Spirits_of_the_Elid',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Desert',
    requirements: {
      quests: [],
      levels: [
        { skill: 'magic', level: 33, boostable: true },
        { skill: 'ranged', level: 37, boostable: true },
        { skill: 'mining', level: 37, boostable: false },
        { skill: 'thieving', level: 37, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'magic', amount: 1000 },
        { skill: 'prayer', amount: 8000 },
        { skill: 'thieving', amount: 1000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Swan-Song',
    name: 'Swan Song',
    wiki_url: 'https://oldschool.runescape.wiki/w/Swan_Song',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Medium',
    series: 'Wise Old Man',
    requirements: {
      quests: ['One Small Favour', 'Garden of Tranquillity'],
      levels: [
        { skill: 'quest', level: 100, boostable: false },
        { skill: 'magic', level: 66, boostable: true },
        { skill: 'cooking', level: 62, boostable: true },
        { skill: 'fishing', level: 62, boostable: true },
        { skill: 'smithing', level: 45, boostable: true },
        { skill: 'firemaking', level: 42, boostable: false },
        { skill: 'crafting', level: 40, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'fishing', amount: 10000 },
        { skill: 'magic', amount: 15000 },
        { skill: 'prayer', amount: 10000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Tai-Bwo-Wannai-Trio',
    name: 'Tai Bwo Wannai Trio',
    wiki_url: 'https://oldschool.runescape.wiki/w/Tai_Bwo_Wannai_Trio',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Karamja',
    requirements: {
      quests: [],
      levels: [
        { skill: 'agility', level: 15, boostable: false },
        { skill: 'cooking', level: 30, boostable: false },
        { skill: 'fishing', level: 5, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'attack', amount: 2500 },
        { skill: 'cooking', amount: 5000 },
        { skill: 'fishing', amount: 5000 },
        { skill: 'strength', amount: 2500 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Tale-of-the-Righteous',
    name: 'Tale of the Righteous',
    wiki_url: 'https://oldschool.runescape.wiki/w/Tale_of_the_Righteous',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Great Kourend',
    requirements: {
      quests: ['Client of Kourend'],
      levels: [
        { skill: 'strength', level: 16, boostable: false },
        { skill: 'mining', level: 10, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: 'Tears-of-Guthix',
    name: 'Tears of Guthix',
    wiki_url: 'https://oldschool.runescape.wiki/w/Tears_of_Guthix_(quest)',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Short',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: 'quest', level: 43, boostable: false },
        { skill: 'firemaking', level: 49, boostable: false },
        { skill: 'crafting', level: 20, boostable: false },
        { skill: 'mining', level: 20, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: 'crafting', amount: 1000 }],
      quest_points: 1,
    },
  },
  {
    id: 'Temple-of-Ikov',
    name: 'Temple of Ikov',
    wiki_url: 'https://oldschool.runescape.wiki/w/Temple_of_Ikov',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Mahjarrat',
    requirements: {
      quests: [],
      levels: [
        { skill: 'thieving', level: 42, boostable: true },
        { skill: 'ranged', level: 40, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'fletching', amount: 8000 },
        { skill: 'ranged', amount: 10500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'The-Ascent-of-Arceuus',
    name: 'The Ascent of Arceuus',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Ascent_of_Arceuus',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Great Kourend',
    requirements: {
      quests: ['Client of Kourend'],
      levels: [{ skill: 'hunter', level: 12, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'hunter', amount: 1500 },
        { skill: 'runecrafting', amount: 500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'The-Corsair-Curse',
    name: 'The Corsair Curse',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Corsair_Curse',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [], quest_points: 2 },
  },
  {
    id: 'The-Depths-of-Despair',
    name: 'The Depths of Despair',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Depths_of_Despair',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Great Kourend',
    requirements: {
      quests: ['Client of Kourend'],
      levels: [{ skill: 'agility', level: 18, boostable: false }],
    },
    rewards: {
      experience: [{ skill: 'agility', amount: 1500 }],
      quest_points: 1,
    },
  },
  {
    id: 'The-Dig-Site',
    name: 'The Dig Site',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Dig_Site',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'The Return of Zaros',
    requirements: {
      quests: [],
      levels: [
        { skill: 'agility', level: 10, boostable: false },
        { skill: 'herblore', level: 10, boostable: false },
        { skill: 'thieving', level: 25, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'herblore', amount: 2000 },
        { skill: 'mining', amount: 15300 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'The-Eyes-of-Glouphrie',
    name: 'The Eyes of Glouphrie',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Eyes_of_Glouphrie',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: 'Gnome',
    requirements: {
      quests: [],
      levels: [
        { skill: 'construction', level: 5, boostable: false },
        { skill: 'magic', level: 46, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'construction', amount: 250 },
        { skill: 'magic', amount: 12000 },
        { skill: 'runecrafting', amount: 6000 },
        { skill: 'woodcutting', amount: 2500 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'The-Feud',
    name: 'The Feud',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Feud',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Desert',
    requirements: {
      quests: [],
      levels: [{ skill: 'thieving', level: 30, boostable: true }],
    },
    rewards: {
      experience: [{ skill: 'thieving', amount: 15000 }],
      quest_points: 1,
    },
  },
  {
    id: 'The-Forsaken-Tower',
    name: 'The Forsaken Tower',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Forsaken_Tower',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: 'Great Kourend',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: 'mining', amount: 500 },
        { skill: 'smithing', amount: 500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'The-Fremennik-Exiles',
    name: 'The Fremennik Exiles',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Fremennik_Exiles',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Medium',
    series: 'Fremennik',
    requirements: {
      quests: [
        'The Fremennik Isles',
        'Lunar Diplomacy',
        'Mountain Daughter',
        "Heroes' Quest",
      ],
      levels: [
        { skill: 'crafting', level: 65, boostable: false },
        { skill: 'slayer', level: 60, boostable: false },
        { skill: 'smithing', level: 60, boostable: false },
        { skill: 'fishing', level: 60, boostable: false },
        { skill: 'runecrafting', level: 55, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 15000 },
        { skill: 'runecrafting', amount: 5000 },
        { skill: 'slayer', amount: 15000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'The-Fremennik-Isles',
    name: 'The Fremennik Isles',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Fremennik_Isles',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [
        { skill: 'construction', level: 20, boostable: false },
        { skill: 'agility', level: 40, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'construction', amount: 5000 },
        { skill: 'crafting', amount: 5000 },
        { skill: 'woodcutting', amount: 10000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'The-Fremennik-Trials',
    name: 'The Fremennik Trials',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Fremennik_Trials',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Fremennik',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: 'agility', amount: 2812 },
        { skill: 'attack', amount: 2812 },
        { skill: 'crafting', amount: 2812 },
        { skill: 'defence', amount: 2812 },
        { skill: 'fishing', amount: 2812 },
        { skill: 'fletching', amount: 2812 },
        { skill: 'hitpoints', amount: 2812 },
        { skill: 'strength', amount: 2812 },
        { skill: 'thieving', amount: 2812 },
        { skill: 'woodcutting', amount: 2812 },
      ],
      quest_points: 3,
    },
  },
  {
    id: 'The-Giant-Dwarf',
    name: 'The Giant Dwarf',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Giant_Dwarf',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: 'Rise of the Red Axe',
    requirements: {
      quests: [],
      levels: [
        { skill: 'crafting', level: 12, boostable: false },
        { skill: 'firemaking', level: 16, boostable: false },
        { skill: 'magic', level: 33, boostable: false },
        { skill: 'thieving', level: 14, boostable: false },
        { skill: 'mining', level: 20, boostable: false },
        { skill: 'smithing', level: 20, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 2500 },
        { skill: 'firemaking', amount: 1500 },
        { skill: 'magic', amount: 1500 },
        { skill: 'mining', amount: 2500 },
        { skill: 'smithing', amount: 2500 },
        { skill: 'thieving', amount: 1500 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'The-Golem',
    name: 'The Golem',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Golem',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [
        { skill: 'crafting', level: 20, boostable: false },
        { skill: 'thieving', level: 25, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 1000 },
        { skill: 'thieving', amount: 1000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'The-Grand-Tree',
    name: 'The Grand Tree',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Grand_Tree',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Gnome',
    requirements: {
      quests: [],
      levels: [{ skill: 'agility', level: 25, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 7900 },
        { skill: 'attack', amount: 18400 },
        { skill: 'magic', amount: 2150 },
      ],
      quest_points: 5,
    },
  },
  {
    id: 'The-Great-Brain-Robbery',
    name: 'The Great Brain Robbery',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Great_Brain_Robbery',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Pirate',
    requirements: {
      quests: [
        'Creature of Fenkenstrain',
        'Cabin Fever',
        'Pirate Pete subquest of Recipe for Disaster',
      ],
      levels: [
        { skill: 'crafting', level: 16, boostable: false },
        { skill: 'construction', level: 30, boostable: false },
        { skill: 'prayer', level: 50, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'construction', amount: 2000 },
        { skill: 'crafting', amount: 3000 },
        { skill: 'prayer', amount: 6000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'The-Hand-in-the-Sand',
    name: 'The Hand in the Sand',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Hand_in_the_Sand',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 9000 },
        { skill: 'thieving', amount: 1000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'The-Knights-Sword',
    name: "The Knight's Sword",
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Knight%27s_Sword',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: 'mining', level: 10, boostable: false }],
    },
    rewards: {
      experience: [{ skill: 'smithing', amount: 12725 }],
      quest_points: 1,
    },
  },
  {
    id: 'The-Lost-Tribe',
    name: 'The Lost Tribe',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Lost_Tribe',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Dorgeshuun',
    requirements: {
      quests: [],
      levels: [
        { skill: 'agility', level: 13, boostable: false },
        { skill: 'thieving', level: 13, boostable: false },
        { skill: 'mining', level: 17, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: 'mining', amount: 3000 }],
      quest_points: 1,
    },
  },
  {
    id: 'The-Queen-of-Thieves',
    name: 'The Queen of Thieves',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Queen_of_Thieves',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Great Kourend',
    requirements: {
      quests: ['Client of Kourend'],
      levels: [{ skill: 'thieving', level: 20, boostable: false }],
    },
    rewards: {
      experience: [{ skill: 'thieving', amount: 2000 }],
      quest_points: 1,
    },
  },
  {
    id: 'The-Restless-Ghost',
    name: 'The Restless Ghost',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Restless_Ghost',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short (<10 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'prayer', amount: 1125 }],
      quest_points: 1,
    },
  },
  {
    id: 'Sins-of-the-Father',
    name: 'Sins of the Father',
    wiki_url: 'https://oldschool.runescape.wiki/w/Sins_of_the_Father',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Master',
    length: 'Long',
    series: null,
    requirements: {
      quests: [
        'Vampyre Slayer',
        'A Taste of Hope',
        'Darkness of Hallowvale',
        'In Aid of the Myreque',
        'In Search of the Myreque',
        'Nature Spirit',
        'Priest in Peril',
        'The Restless Ghost',
      ],
      levels: [
        { skill: 'woodcutting', level: 62, boostable: false },
        { skill: 'fletching', level: 60, boostable: false },
        { skill: 'crafting', level: 56, boostable: false },
        { skill: 'agility', level: 52, boostable: false },
        { skill: 'attack', level: 50, boostable: false },
        { skill: 'slayer', level: 50, boostable: false },
        { skill: 'magic', level: 49, boostable: false },
      ],
    },
    rewards: {
      experience: [],
      quest_points: 2,
      Items: ['Blisterwood flail'],
      other: [
        'Access to Darkmeyer',
        'A tome of experience, granting 15,000 experience to any three skills (level 60 or higher). Can be the same skill.',
        "Darkmeyer teleport via Drakan's medallion",
        'Boat travel between Burgh de Rott, Slepe and the Icyene Graveyard',
      ],
    },
  },
  {
    id: 'The-Slug-Menace',
    name: 'The Slug Menace',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Slug_Menace',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium - Long',
    series: 'Sea Slug',
    requirements: {
      quests: [],
      levels: [
        { skill: 'crafting', level: 30, boostable: false },
        { skill: 'runecrafting', level: 30, boostable: true },
        { skill: 'slayer', level: 30, boostable: true },
        { skill: 'thieving', level: 30, boostable: true },
      ],
    },
    rewards: {
      experience: [
        { skill: 'crafting', amount: 3500 },
        { skill: 'runecrafting', amount: 3500 },
        { skill: 'thieving', amount: 3500 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'The-Tourist-Trap',
    name: 'The Tourist Trap',
    wiki_url: 'https://oldschool.runescape.wiki/w/The_Tourist_Trap',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Desert',
    requirements: {
      quests: [],
      levels: [
        { skill: 'fletching', level: 10, boostable: false },
        { skill: 'smithing', level: 20, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 2 },
  },
  {
    id: 'Throne-of-Miscellania',
    name: 'Throne of Miscellania',
    wiki_url: 'https://oldschool.runescape.wiki/w/Throne_of_Miscellania',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Fremennik',
    requirements: {
      quests: [],
      levels: [
        { skill: 'woodcutting', level: 45, boostable: false },
        { skill: 'farming', level: 10, boostable: false },
        { skill: 'mining', level: 30, boostable: false },
        { skill: 'fishing', level: 35, boostable: false },
      ],
    },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: 'Tower-of-Life',
    name: 'Tower of Life',
    wiki_url: 'https://oldschool.runescape.wiki/w/Tower_of_Life',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Medium',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: 'construction', level: 10, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'construction', amount: 1000 },
        { skill: 'crafting', amount: 500 },
        { skill: 'thieving', amount: 500 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Tree-Gnome-Village',
    name: 'Tree Gnome Village',
    wiki_url: 'https://oldschool.runescape.wiki/w/Tree_Gnome_Village',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: 'Gnome',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'attack', amount: 11450 }],
      quest_points: 2,
    },
  },
  {
    id: 'Tribal-Totem',
    name: 'Tribal Totem',
    wiki_url: 'https://oldschool.runescape.wiki/w/Tribal_Totem',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: null,
    requirements: {
      quests: [],
      levels: [{ skill: 'thieving', level: 21, boostable: false }],
    },
    rewards: {
      experience: [{ skill: 'thieving', amount: 1775 }],
      quest_points: 1,
    },
  },
  {
    id: 'Troll-Romance',
    name: 'Troll Romance',
    wiki_url: 'https://oldschool.runescape.wiki/w/Troll_Romance',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Medium',
    series: 'Troll',
    requirements: { quests: ['Troll Stronghold'], levels: [] },
    rewards: {
      experience: [
        { skill: 'agility', amount: 8000 },
        { skill: 'strength', amount: 4000 },
      ],
      quest_points: 2,
    },
  },
  {
    id: 'Troll-Stronghold',
    name: 'Troll Stronghold',
    wiki_url: 'https://oldschool.runescape.wiki/w/Troll_Stronghold',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Short - Medium',
    series: 'Troll',
    requirements: {
      quests: [],
      levels: [{ skill: 'agility', level: 15, boostable: false }],
    },
    rewards: { experience: [], quest_points: 1 },
  },
  {
    id: 'Underground-Pass',
    name: 'Underground Pass',
    wiki_url: 'https://oldschool.runescape.wiki/w/Underground_Pass',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Experienced',
    length: 'Long',
    series: 'Elf',
    requirements: {
      quests: ['Biohazard'],
      levels: [{ skill: 'ranged', level: 25, boostable: false }],
    },
    rewards: {
      experience: [
        { skill: 'agility', amount: 3000 },
        { skill: 'attack', amount: 3000 },
      ],
      quest_points: 5,
    },
  },
  {
    id: 'Vampire-Slayer',
    name: 'Vampire Slayer',
    wiki_url: 'https://oldschool.runescape.wiki/w/Vampire_Slayer',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'attack', amount: 4825 }],
      quest_points: 3,
    },
  },
  {
    id: 'Wanted',
    name: 'Wanted!',
    wiki_url: 'https://oldschool.runescape.wiki/w/Wanted!',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Temple Knight',
    requirements: {
      quests: [
        'Recruitment Drive',
        'Rune Mysteries',
        'The Lost Tribe',
        'Priest in Peril',
      ],
      levels: [{ skill: 'quest', level: 32, boostable: false }],
    },
    rewards: {
      experience: [{ skill: 'slayer', amount: 5000 }],
      quest_points: 1,
    },
  },
  {
    id: 'Watchtower',
    name: 'Watchtower',
    wiki_url: 'https://oldschool.runescape.wiki/w/Watchtower',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Long',
    series: 'Ogre',
    requirements: {
      quests: [],
      levels: [
        { skill: 'magic', level: 15, boostable: false },
        { skill: 'thieving', level: 15, boostable: false },
        { skill: 'agility', level: 25, boostable: false },
        { skill: 'herblore', level: 14, boostable: false },
        { skill: 'mining', level: 40, boostable: false },
      ],
    },
    rewards: {
      experience: [{ skill: 'magic', amount: 15250 }],
      quest_points: 4,
    },
  },
  {
    id: 'Waterfall-Quest',
    name: 'Waterfall Quest',
    wiki_url: 'https://oldschool.runescape.wiki/w/Waterfall_Quest',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium (10-20 minutes)',
    series: 'Elf, Gnome',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: 'attack', amount: 13750 },
        { skill: 'strength', amount: 13750 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'What-Lies-Below',
    name: 'What Lies Below',
    wiki_url: 'https://oldschool.runescape.wiki/w/What_Lies_Below',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short - Medium',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [
        { skill: 'defence', amount: 2000 },
        { skill: 'runecrafting', amount: 8000 },
      ],
      quest_points: 1,
    },
  },
  {
    id: 'Witchs-House',
    name: "Witch's House",
    wiki_url: 'https://oldschool.runescape.wiki/w/Witch%27s_House',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Short',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [{ skill: 'hitpoints', amount: 6325 }],
      quest_points: 4,
    },
  },
  {
    id: 'Witchs-Potion',
    name: "Witch's Potion",
    wiki_url: 'https://oldschool.runescape.wiki/w/Witch%27s_Potion',
    is_members_only: false,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short (<5 minutes)',
    series: null,
    requirements: { quests: [], levels: [] },
    rewards: { experience: [{ skill: 'magic', amount: 325 }], quest_points: 1 },
  },
  {
    id: 'X-Marks-the-Spot',
    name: 'X Marks the Spot',
    wiki_url: 'https://oldschool.runescape.wiki/w/X_Marks_the_Spot',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Novice',
    length: 'Short',
    series: 'Great Kourend',
    requirements: { quests: [], levels: [] },
    rewards: {
      experience: [],
      quest_points: 1,
      other: [
        '200 coins',
        "Antique lamp which provides 300 XP in a skill of the player's choosing.",
        'A beginner clue scroll (only if the player does not have one in their possession; can be claimed later if players had one in their possession already)',
      ],
    },
  },
  {
    id: 'Zogre-Flesh-Eaters',
    name: 'Zogre Flesh Eaters',
    wiki_url: 'https://oldschool.runescape.wiki/w/Zogre_Flesh_Eaters',
    is_members_only: true,
    is_miniquest: false,
    difficulty: 'Intermediate',
    length: 'Medium',
    series: 'Ogre',
    requirements: {
      quests: ['Big Chompy Bird Hunting', 'Jungle Potion'],
      levels: [
        { skill: 'smithing', level: 4, boostable: false },
        { skill: 'herblore', level: 8, boostable: false },
        { skill: 'ranged', level: 30, boostable: false },
        { skill: 'fletching', level: 30, boostable: false },
        { skill: 'strength', level: 10, boostable: false },
        { skill: 'prayer', level: 43, boostable: false },
      ],
    },
    rewards: {
      experience: [
        { skill: 'fletching', amount: 2000 },
        { skill: 'herblore', amount: 2000 },
        { skill: 'ranged', amount: 2000 },
      ],
      quest_points: 1,
    },
  },
];
